In [ ]:
# Please change the following file write location then simply run these cell in order 
# 
# No Guarentee on randomness or schema holding
# 
# Works for both Real & PSQL (see readme)
  
# Directory
directory = "<Change to the file name"

parent_dir = "<Change to where you want the files>"

In [1]:
import names
import os
import pandas as pd
import random
from datetime import datetime, date, timedelta
import datetime

# customer table

df_cities = pd.read_csv("Desktop/Personal Project/gb.csv")

df_branches = df_cities.head(20)

df_cust = pd.DataFrame(columns = ["uid","name","branch"])


for i in range(200):
    df_len = len(df_cust)
    df_temp = df_branches.sample()
    df_temp = df_temp.reset_index()
    temp = df_temp.loc[0,"city"]
    
    df_cust.loc[df_len,"uid"] = df_len
    df_cust.loc[df_len,"name"] = names.get_full_name()
    df_cust.loc[df_len,"branch"] = temp

In [2]:
print(display(df_cust))

     uid               name       branch
0      0       Steve Coffie  Southampton
1      1       Eunice Ellis      Bristol
2      2  Maria Christensen   Portsmouth
3      3     Pauline Mouser      Glasgow
4      4      Walter Barton   Manchester
..   ...                ...          ...
195  195    Roberto Meacham  Southampton
196  196    Norman Bradford      Reading
197  197         John Lynch     Caerdydd
198  198        Eric Hannah      Glasgow
199  199     Cleo Greenfeld     Coventry

[200 rows x 3 columns]

None

In [3]:
# books
from random_word import RandomWords
r = RandomWords()

types_fiction = ["SCI-FI", "FANTASY", "ADVENTURE", "MYSTERY", "CRIME", "HISTORY", "ROMANCE", "HORROR"]
types_non_fic = ["BIOGRAPHY", "SELF-HELP", "HISTORY", "TRAVEL", "COOKING", "CRIME", "REFERENCE"]
genra_list = ["FICTION","NON-FICTION"]

df_books = pd.DataFrame(columns=["title","author","genre","subgenre"])

for j in range(200):
    print(j)
    
    genra = random.choice(genra_list)
    if genra == "FICTION":
        sub = random.choice(types_fiction)
    else:
        sub = random.choice(types_non_fic)
        genra = "NON-FICTION"
    
    df_len = len(df_books)
    df_books.loc[df_len,"genre"] = genra
    df_books.loc[df_len,"subgenre"] = sub
    df_books.loc[df_len,"title"] = str(r.get_random_word()+" "+r.get_random_word())
    df_books.loc[df_len,"author"] = names.get_full_name()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199

In [4]:
# copies

df_copies = pd.DataFrame(columns=["unquie","title","author","branch"])

for k in range(400):
    df_temp = df_cust.sample()
    df_temp = df_temp.reset_index()
    temp = df_temp.loc[0,"branch"]
    
    df_temp_two = df_books.sample()
    df_temp_two = df_temp_two.reset_index()
    print(df_temp_two)
    
    if (k%5 == 0):
        r = 0
        for r in range(random.randint(1,14)):
            df_len = len(df_copies)
            df_copies.loc[df_len,"unquie"] = df_len+1337
            df_copies.loc[df_len,"title"] = df_temp_two.loc[0,"title"] 
            df_copies.loc[df_len,"author"] = df_temp_two.loc[0,"author"] 
            df_copies.loc[df_len,"branch"] = temp


    df_len = len(df_copies)
    df_copies.loc[df_len,"unquie"] = df_len+1337
    df_copies.loc[df_len,"title"] = df_temp_two.loc[0,"title"] 
    df_copies.loc[df_len,"author"] = df_temp_two.loc[0,"author"] 
    df_copies.loc[df_len,"branch"] = temp
    
#     print(df_copies.loc[df_len])

   index                  title      author    genre subgenre
0    114  unstablished frousier  Tim Lawson  FICTION   HORROR
   index                title      author        genre   subgenre
0    158  magmata cloudlessly  Lisa Grant  NON-FICTION  SELF-HELP
   index             title              author    genre subgenre
0     66  fecche teniacide  Raymond Richardson  FICTION   HORROR
   index                        title             author    genre subgenre
0    125  counterattestation percents  Brittany Robinson  FICTION  HISTORY
   index                title         author        genre   subgenre
0     28  explicative gladded  Leslie Wisner  NON-FICTION  REFERENCE
   index                  title      author        genre subgenre
0     61  supraworld siphonaria  Jose Mills  NON-FICTION  HISTORY
   index                  title        author        genre   subgenre
0     96  cephalodiscida toryfy  Carol Guzman  NON-FICTION  SELF-HELP
   index                    title           author        genre   subgenre
0     75  settees overmultiplying  Jane Richardson  NON-FICTION  BIOGRAPHY
   index                     title            author        genre   subgenre
0    146  druthers palaeographical  Patrick Manrique  NON-FICTION  REFERENCE
   index                 title            author        genre subgenre
0     36  diazonium chamaerops  Carolyn Sullivan  NON-FICTION  HISTORY
   index              title         author    genre   subgenre
0    180  oleander unespied  Tommie Bright  FICTION  ADVENTURE
   index             title        author        genre   subgenre
0    167  aptly zygotomere  Robert Rados  NON-FICTION  BIOGRAPHY
   index           title        author    genre subgenre
0     43  eably admiring  Rose Sorrels  FICTION   HORROR
   index                  title             author    genre subgenre
0     73  pocketbook semionotus  Margaret Chandler  FICTION   SCI-FI
   index                     title        author    genre subgenre
0    156  dynastically proganosaur  Randell Pell  FICTION  HISTORY
   index                     title            author        genre   subgenre
0    146  druthers palaeographical  Patrick Manrique  NON-FICTION  REFERENCE
   index                      title           author        genre   subgenre
0     67  unarousable inequicostate  Patricia Duffin  NON-FICTION  BIOGRAPHY
   index                title        author        genre   subgenre
0     45  preobtain vaporific  Barry Greene  NON-FICTION  SELF-HELP
   index         title           author        genre subgenre
0    186  uncurbed hrs  Nancy Callender  NON-FICTION   TRAVEL
   index                        title             author    genre subgenre
0    125  counterattestation percents  Brittany Robinson  FICTION  HISTORY
   index                  title             author    genre subgenre
0     73  pocketbook semionotus  Margaret Chandler  FICTION   SCI-FI
   index                    title        author        genre   subgenre
0     95  madrassah sclerectomies  Alan Conyers  NON-FICTION  REFERENCE
   index                  title             author    genre subgenre
0     73  pocketbook semionotus  Margaret Chandler  FICTION   SCI-FI
   index               title            author    genre subgenre
0    177  misguesses jackeen  Antonio Santiago  FICTION   HORROR
   index                 title             author    genre   subgenre
0    131  nonhunting hoarstone  Gwendolyn Pollard  FICTION  ADVENTURE
   index                  title          author        genre   subgenre
0     76  chancefully crayonist  William Miller  NON-FICTION  BIOGRAPHY
   index                 title       author        genre   subgenre
0    112  suppletively plopped  Patsy Wells  NON-FICTION  REFERENCE
   index                            title         author        genre subgenre
0     20  superindustriousness dealership  Alexis Wright  NON-FICTION  HISTORY
   index                    title       author    genre subgenre
0    126  protandrism multisector  Daniel Lacy  FICTION    CRIME
   index                   title      author    genre   subgenre
0     46  megillah interlocutrix  John Glass  FICTION  ADVENTURE
   index                 title        author    genre subgenre
0    109  springworm thirsting  German Derck  FICTION   SCI-FI
   index                    title       author    genre subgenre
0    126  protandrism multisector  Daniel Lacy  FICTION    CRIME
   index           title         author        genre   subgenre
0    187  downbear quais  Amanda Savage  NON-FICTION  BIOGRAPHY
   index          title     author    genre subgenre
0     84  playa heiress  Shawn Kim  FICTION  MYSTERY
   index               title        author        genre subgenre
0    124  cropsick hoggaster  Dawn Lambdin  NON-FICTION  COOKING
   index                title           author    genre subgenre
0    160  lucifugous piassaba  Anthony Jackson  FICTION  FANTASY
   index               title         author    genre   subgenre
0    106  pearlfish irrupted  Glenda French  FICTION  ADVENTURE
   index               title         author    genre subgenre
0     92  bookmate spiderier  Luke Blodgett  FICTION    CRIME
   index                title         author        genre   subgenre
0     28  explicative gladded  Leslie Wisner  NON-FICTION  REFERENCE
   index                       title           author    genre subgenre
0    144  monothelitic hysterocystic  Regina Griswell  FICTION   HORROR
   index                      title        author    genre subgenre
0    139  undreadfully microsthenes  Michael King  FICTION  HISTORY
   index                title         author        genre   subgenre
0     28  explicative gladded  Leslie Wisner  NON-FICTION  REFERENCE
   index                  title           author        genre   subgenre
0    191  balanus thysanuriform  Stephanie Lynch  NON-FICTION  BIOGRAPHY
   index                   title         author    genre subgenre
0     31  restraightening fusing  John Peterson  FICTION   SCI-FI
   index                      title         author    genre subgenre
0      4  diamant quadrituberculate  Jesse Prevost  FICTION   SCI-FI
   index                 title        author        genre subgenre
0     11  adjoined archprimate  Randy Jacoby  NON-FICTION    CRIME
   index                       title      author        genre subgenre
0     77  disassembling exhaustively  Jeri Rolfe  NON-FICTION  COOKING
   index               title         author        genre   subgenre
0    195  zoogleas tagboards  Carol Murphey  NON-FICTION  SELF-HELP
   index                  title        author        genre   subgenre
0     96  cephalodiscida toryfy  Carol Guzman  NON-FICTION  SELF-HELP
   index         title         author    genre subgenre
0     30  mascons akal  Mary Thompson  FICTION    CRIME
   index        title             author        genre subgenre
0     40  cavicorn nm  William Lambrecht  NON-FICTION  HISTORY
   index                   title            author        genre subgenre
0    130  thoughtlet thiocyanide  Carlton Donnelly  NON-FICTION    CRIME
   index                title            author    genre subgenre
0     41  smallen lilacthroat  Janice Macdonald  FICTION  HISTORY
   index                      title         author    genre subgenre
0      6  dissemblers bluestockings  Dino Schwalbe  FICTION   HORROR
   index                    title        author        genre   subgenre
0     95  madrassah sclerectomies  Alan Conyers  NON-FICTION  REFERENCE
   index             title            author        genre   subgenre
0     34  cygninae balarao  Clarence Andrews  NON-FICTION  SELF-HELP
   index               title             author        genre subgenre
0    111  footpaddery haemic  Rebecca Christner  NON-FICTION  COOKING
   index                  title             author    genre subgenre
0     73  pocketbook semionotus  Margaret Chandler  FICTION   SCI-FI
   index                        title           author    genre subgenre
0    182  preenvironmental electrical  Angela Mccurley  FICTION  MYSTERY
   index               title        author        genre subgenre
0     33  cassabanana meline  Robert Irwin  NON-FICTION   TRAVEL
   index                       title           author    genre subgenre
0    144  monothelitic hysterocystic  Regina Griswell  FICTION   HORROR
   index                title      author        genre   subgenre
0    158  magmata cloudlessly  Lisa Grant  NON-FICTION  SELF-HELP
   index              title          author        genre subgenre
0    155  hexachord leverer  Robin Eitniear  NON-FICTION  HISTORY
   index              title      author        genre subgenre
0    105  scranky semitones  Sue Seiler  NON-FICTION    CRIME
   index              title         author        genre subgenre
0      0  kansans radiology  Laura Goodall  NON-FICTION   TRAVEL
   index           title        author        genre subgenre
0    145  mirkiest anour  Angela Brock  NON-FICTION  COOKING
   index                  title        author        genre   subgenre
0     96  cephalodiscida toryfy  Carol Guzman  NON-FICTION  SELF-HELP
   index                 title       author        genre   subgenre
0    112  suppletively plopped  Patsy Wells  NON-FICTION  REFERENCE
   index                 title        author        genre subgenre
0    193  muscicolous menehune  Laura Taylor  NON-FICTION   TRAVEL
   index                  title           author        genre   subgenre
0    191  balanus thysanuriform  Stephanie Lynch  NON-FICTION  BIOGRAPHY
   index                 title         author        genre subgenre
0    115  lipwork disagreeable  Herbert Rains  NON-FICTION  COOKING
   index                        title           author        genre subgenre
0      9  dithionic semimicrochemical  Michael Grisham  NON-FICTION    CRIME
   index                    title       author    genre subgenre
0    126  protandrism multisector  Daniel Lacy  FICTION    CRIME
   index               title            author    genre subgenre
0    177  misguesses jackeen  Antonio Santiago  FICTION   HORROR
   index              title        author    genre subgenre
0    198  mashru lignocaine  Connie Brown  FICTION   SCI-FI
   index                  title        author    genre subgenre
0     12  masterling declaiming  Donald White  FICTION    CRIME
   index                title           author    genre subgenre
0    160  lucifugous piassaba  Anthony Jackson  FICTION  FANTASY
   index             title        author        genre   subgenre
0    167  aptly zygotomere  Robert Rados  NON-FICTION  BIOGRAPHY
   index              title         author        genre subgenre
0      0  kansans radiology  Laura Goodall  NON-FICTION   TRAVEL
   index                   title             author    genre subgenre
0    128  anamorphous undersward  Christopher Jones  FICTION    CRIME
   index                title          author        genre   subgenre
0     14  eucosmid missteered  Gladys Fischer  NON-FICTION  SELF-HELP
   index                 title      author    genre subgenre
0    108  magistracies forblow  Jon Lozano  FICTION   SCI-FI
   index                      title         author    genre subgenre
0      6  dissemblers bluestockings  Dino Schwalbe  FICTION   HORROR
   index                 title          author    genre subgenre
0    162  magnetizable rigadon  April Williams  FICTION  ROMANCE
   index          title        author        genre subgenre
0    123  lira spenders  Teresa Ervin  NON-FICTION   TRAVEL
   index          title     author        genre subgenre
0     83  durgah deckel  Rose Nash  NON-FICTION  COOKING

   index                   title      author    genre   subgenre
0     46  megillah interlocutrix  John Glass  FICTION  ADVENTURE
   index                title            author    genre subgenre
0     41  smallen lilacthroat  Janice Macdonald  FICTION  HISTORY
   index                      title           author        genre   subgenre
0     67  unarousable inequicostate  Patricia Duffin  NON-FICTION  BIOGRAPHY
   index                title           author    genre subgenre
0    160  lucifugous piassaba  Anthony Jackson  FICTION  FANTASY
   index                title      author    genre subgenre
0     55  notional unblocking  Helen Weis  FICTION  FANTASY
   index                  title            author    genre subgenre
0     29  nonreticently lindsay  Eddie Strzelecki  FICTION  HISTORY
   index                   title          author    genre subgenre
0     89  histophysiologic asuri  Rachel Johnson  FICTION   HORROR
   index          title     author        genre subgenre
0     83  durgah deckel  Rose Nash  NON-FICTION  COOKING
   index           title        author        genre subgenre
0    145  mirkiest anour  Angela Brock  NON-FICTION  COOKING
   index              title          author        genre   subgenre
0     35  mousehound rethaw  Michael Holmes  NON-FICTION  BIOGRAPHY
   index               title            author    genre subgenre
0    177  misguesses jackeen  Antonio Santiago  FICTION   HORROR
   index                  title     author    genre subgenre
0     22  speeders unremembered  Van Moore  FICTION  FANTASY
   index           title        author    genre subgenre
0     70  joyce selfcide  Calvin Coury  FICTION  HISTORY
   index                    title       author        genre   subgenre
0      8  scolopendrelloid gabbai  Eloy Sexton  NON-FICTION  BIOGRAPHY
   index               title         author    genre subgenre
0     92  bookmate spiderier  Luke Blodgett  FICTION    CRIME
   index                title         author        genre   subgenre
0     28  explicative gladded  Leslie Wisner  NON-FICTION  REFERENCE
   index                 title        author        genre subgenre
0    193  muscicolous menehune  Laura Taylor  NON-FICTION   TRAVEL
   index                            title     author        genre subgenre
0    133  pseudoceratites intramembranous  Tony Lane  NON-FICTION  HISTORY
   index                   title             author    genre subgenre
0    128  anamorphous undersward  Christopher Jones  FICTION    CRIME
   index                  title       author    genre subgenre
0     16  blastplate electorial  Derek Leroy  FICTION  HISTORY
   index                title         author    genre subgenre
0     68  beefcake gonococcus  Jonathan Peck  FICTION   HORROR
   index              title        author    genre subgenre
0    118  candollea poodler  Donna Mayhew  FICTION  HISTORY
   index                     title            author        genre   subgenre
0    146  druthers palaeographical  Patrick Manrique  NON-FICTION  REFERENCE
   index           title        author        genre subgenre
0    145  mirkiest anour  Angela Brock  NON-FICTION  COOKING
   index              title            author    genre subgenre
0     87  uplit proprietory  Shirley Stinnett  FICTION  ROMANCE
   index                title      author    genre subgenre
0     55  notional unblocking  Helen Weis  FICTION  FANTASY
   index            title            author    genre subgenre
0    192  dullness spydom  Christine Thomas  FICTION    CRIME
   index                            title        author    genre subgenre
0    141  ultranationalist uneffusiveness  Sheri Miller  FICTION  MYSTERY
   index               title        author        genre subgenre
0    124  cropsick hoggaster  Dawn Lambdin  NON-FICTION  COOKING
   index              title           author        genre subgenre
0     81  dawdle interludes  Debra Vannorman  NON-FICTION  HISTORY
   index                    title        author    genre subgenre
0     86  slateful superfinancing  Ruby Fortson  FICTION    CRIME
   index                     title      author    genre subgenre
0    181  relentless unpersecutive  Joann Glud  FICTION    CRIME
   index           title         author    genre subgenre
0     52  gooier snuffed  Maryjo Nowlin  FICTION    CRIME
   index         title            author    genre subgenre
0    168  bevvy upband  Jessica Menchaca  FICTION  ROMANCE
   index               title      author    genre subgenre
0    172  liking initiatress  Nancy Chan  FICTION    CRIME
   index                  title       author    genre subgenre
0     16  blastplate electorial  Derek Leroy  FICTION  HISTORY
   index                     title            author        genre subgenre
0    159  primevalism contrastment  Sherri Altmiller  NON-FICTION   TRAVEL
   index            title       author        genre subgenre
0    151  tritonal canyon  Melvin Sims  NON-FICTION  HISTORY
   index             title              author    genre subgenre
0     66  fecche teniacide  Raymond Richardson  FICTION   HORROR
   index                title       author    genre subgenre
0     54  hardbound slynesses  James Dixon  FICTION  FANTASY
   index                    title       author    genre subgenre
0    126  protandrism multisector  Daniel Lacy  FICTION    CRIME
   index                  title        author        genre subgenre
0    157  ectomesoblast distune  Alonzo Bench  NON-FICTION    CRIME
   index                    title              author        genre subgenre
0     48  pseudoneuroptera zoners  Jacqueline Schmidt  NON-FICTION    CRIME
   index                     title          author    genre subgenre
0    188  diagrammed noncoincident  Sherry Trotter  FICTION   SCI-FI
   index                    title       author        genre   subgenre
0      8  scolopendrelloid gabbai  Eloy Sexton  NON-FICTION  BIOGRAPHY
   index                 title        author        genre subgenre
0     11  adjoined archprimate  Randy Jacoby  NON-FICTION    CRIME
   index              title      author        genre subgenre
0    105  scranky semitones  Sue Seiler  NON-FICTION    CRIME
   index                title        author    genre subgenre
0     72  dittoed anematizing  Rocky Garcia  FICTION   HORROR
   index            title         author    genre   subgenre
0    132  plutocrat spalt  Lauren Hopton  FICTION  ADVENTURE
   index              title        author    genre subgenre
0    118  candollea poodler  Donna Mayhew  FICTION  HISTORY
   index               title       author        genre subgenre
0      1  dilemmas unerected  Alan Ritter  NON-FICTION   TRAVEL
   index                    title         author        genre subgenre
0    102  anticyclolysis shattery  Jeremy Kasper  NON-FICTION    CRIME
   index                title        author        genre   subgenre
0     45  preobtain vaporific  Barry Greene  NON-FICTION  SELF-HELP
   index             title         author        genre   subgenre
0    170  plateasm cryable  Robert Munson  NON-FICTION  SELF-HELP
   index                   title         author        genre subgenre
0     60  whitewashed forfeiture  Erick Newkirk  NON-FICTION   TRAVEL
   index                 title         author        genre subgenre
0    175  unfurrowed tapayaxin  Judith Harris  NON-FICTION    CRIME
   index                     title      author    genre subgenre
0    181  relentless unpersecutive  Joann Glud  FICTION    CRIME
   index                         title      author    genre subgenre
0     69  multiflagellate inadulterate  John Waite  FICTION  MYSTERY
   index             title        author        genre   subgenre
0    167  aptly zygotomere  Robert Rados  NON-FICTION  BIOGRAPHY
   index               title             author        genre subgenre
0    111  footpaddery haemic  Rebecca Christner  NON-FICTION  COOKING
   index                         title      author    genre subgenre
0     69  multiflagellate inadulterate  John Waite  FICTION  MYSTERY
   index                     title           author        genre   subgenre
0     24  saturnine monotonousness  Martina Vitullo  NON-FICTION  BIOGRAPHY
   index                 title         author        genre subgenre
0    115  lipwork disagreeable  Herbert Rains  NON-FICTION  COOKING
   index               title        author        genre subgenre
0    124  cropsick hoggaster  Dawn Lambdin  NON-FICTION  COOKING
   index          title     author    genre subgenre
0     84  playa heiress  Shawn Kim  FICTION  MYSTERY
   index                title          author        genre   subgenre
0     14  eucosmid missteered  Gladys Fischer  NON-FICTION  SELF-HELP
   index                          title         author    genre subgenre
0    120  nonuniversally straticulation  Edward Norris  FICTION  HISTORY
   index             title        author    genre subgenre
0     44  cinnamyl copious  Inez Jackson  FICTION  HISTORY
   index                   title            author        genre subgenre
0    130  thoughtlet thiocyanide  Carlton Donnelly  NON-FICTION    CRIME
   index             title        author        genre   subgenre
0    167  aptly zygotomere  Robert Rados  NON-FICTION  BIOGRAPHY
   index                       title       author    genre subgenre
0     42  repentantly polyphonically  Sylvia Reid  FICTION  ROMANCE
   index              title        author    genre subgenre
0    110  crumbers naphtali  Leland Miles  FICTION  MYSTERY
   index           title           author        genre   subgenre
0    173  snitch grooper  Stephanie Loder  NON-FICTION  REFERENCE
   index                 title      author    genre subgenre
0    108  magistracies forblow  Jon Lozano  FICTION   SCI-FI
   index                    title         author        genre subgenre
0    102  anticyclolysis shattery  Jeremy Kasper  NON-FICTION    CRIME
   index         title            author    genre subgenre
0    168  bevvy upband  Jessica Menchaca  FICTION  ROMANCE
   index                title             author    genre subgenre
0    113  aglucone misaccount  Betty Catanzarite  FICTION  MYSTERY
   index               title          author    genre subgenre
0    140  ectogenic relented  Alison Coffman  FICTION  MYSTERY
   index                    title            author    genre subgenre
0     80  overcorrupt docibleness  Raymond Anderson  FICTION   SCI-FI
   index              title         author    genre   subgenre
0    180  oleander unespied  Tommie Bright  FICTION  ADVENTURE
   index              title         author        genre subgenre
0     51  prunetol aquarius  Bobbi Chapman  NON-FICTION    CRIME
   index          title        author        genre   subgenre
0     19  acolytus crud  Edward Price  NON-FICTION  BIOGRAPHY
   index               title            author    genre subgenre
0    177  misguesses jackeen  Antonio Santiago  FICTION   HORROR
   index                title       author    genre subgenre
0     54  hardbound slynesses  James Dixon  FICTION  FANTASY
   index                  title        author    genre subgenre
0     12  masterling declaiming  Donald White  FICTION    CRIME
   index           title         author    genre subgenre
0     52  gooier snuffed  Maryjo Nowlin  FICTION    CRIME
   index               title        author        genre subgenre
0    124  cropsick hoggaster  Dawn Lambdin  NON-FICTION  COOKING
   index              title         author        genre subgenre
0     51  prunetol aquarius  Bobbi Chapman  NON-FICTION    CRIME
   index                     title           author    genre subgenre
0     65  congeeing undesirability  Kristy Luttrell  FICTION    CRIME
   index                    title           author        genre   subgenre
0     75  settees overmultiplying  Jane Richardson  NON-FICTION  BIOGRAPHY
   index                      title           author    genre subgenre
0    163  nonunification trilobated  George Grubaugh  FICTION  FANTASY
   index               title             author        genre subgenre
0    111  footpaddery haemic  Rebecca Christner  NON-FICTION  COOKING
   index             title       author    genre subgenre
0    100  lachrymae dunged  James Jones  FICTION   HORROR
   index                    title       author        genre   subgenre
0      8  scolopendrelloid gabbai  Eloy Sexton  NON-FICTION  BIOGRAPHY
   index            title       author        genre subgenre
0    151  tritonal canyon  Melvin Sims  NON-FICTION  HISTORY
   index         title        author    genre subgenre
0    103  resinol bede  Betty Jensen  FICTION   SCI-FI
   index                      title           author        genre   subgenre
0     67  unarousable inequicostate  Patricia Duffin  NON-FICTION  BIOGRAPHY
   index                     title          author    genre subgenre
0    188  diagrammed noncoincident  Sherry Trotter  FICTION   SCI-FI

   index              title        author    genre subgenre
0    110  crumbers naphtali  Leland Miles  FICTION  MYSTERY
   index               title        author        genre subgenre
0     33  cassabanana meline  Robert Irwin  NON-FICTION   TRAVEL
   index             title         author        genre subgenre
0      5  laos nonbarbaric  Matthew Matta  NON-FICTION   TRAVEL
   index                   title            author        genre subgenre
0    130  thoughtlet thiocyanide  Carlton Donnelly  NON-FICTION    CRIME
   index                  title             author    genre subgenre
0     73  pocketbook semionotus  Margaret Chandler  FICTION   SCI-FI
   index                            title        author    genre subgenre
0    141  ultranationalist uneffusiveness  Sheri Miller  FICTION  MYSTERY
   index                     title         author    genre subgenre
0    199  takahe preacknowledgment  Donald Thomas  FICTION  FANTASY
   index                       title        author    genre subgenre
0     15  merrytrotter coconspirator  Robert Davis  FICTION  ROMANCE
   index                    title         author        genre subgenre
0    184  missable propheticality  Martin Priest  NON-FICTION  COOKING
   index           title        author    genre subgenre
0     70  joyce selfcide  Calvin Coury  FICTION  HISTORY
   index          title     author        genre subgenre
0     83  durgah deckel  Rose Nash  NON-FICTION  COOKING
   index           title         author    genre subgenre
0      3  unremote fifth  Dorothea King  FICTION   HORROR
   index                     title           author    genre subgenre
0     65  congeeing undesirability  Kristy Luttrell  FICTION    CRIME
   index                     title            author        genre subgenre
0    159  primevalism contrastment  Sherri Altmiller  NON-FICTION   TRAVEL
   index                     title        author    genre subgenre
0    156  dynastically proganosaur  Randell Pell  FICTION  HISTORY
   index       title         author        genre subgenre
0    178  essays gld  Sherrill Haas  NON-FICTION   TRAVEL
   index              title        author    genre subgenre
0    118  candollea poodler  Donna Mayhew  FICTION  HISTORY
   index           title        author        genre subgenre
0    145  mirkiest anour  Angela Brock  NON-FICTION  COOKING
   index             title         author        genre   subgenre
0    170  plateasm cryable  Robert Munson  NON-FICTION  SELF-HELP
   index                 title       author        genre   subgenre
0    112  suppletively plopped  Patsy Wells  NON-FICTION  REFERENCE
   index               title          author    genre subgenre
0    140  ectogenic relented  Alison Coffman  FICTION  MYSTERY
   index                    title       author    genre subgenre
0    126  protandrism multisector  Daniel Lacy  FICTION    CRIME
   index                   title            author        genre subgenre
0    130  thoughtlet thiocyanide  Carlton Donnelly  NON-FICTION    CRIME
   index                 title        author        genre subgenre
0    193  muscicolous menehune  Laura Taylor  NON-FICTION   TRAVEL
   index                     title            author        genre subgenre
0    159  primevalism contrastment  Sherri Altmiller  NON-FICTION   TRAVEL
   index         title           author        genre subgenre
0    186  uncurbed hrs  Nancy Callender  NON-FICTION   TRAVEL
   index               title            author    genre subgenre
0    177  misguesses jackeen  Antonio Santiago  FICTION   HORROR
   index                  title            author        genre subgenre
0     71  pillory squamomastoid  Michael Thompson  NON-FICTION  COOKING
   index                 title         author        genre subgenre
0    175  unfurrowed tapayaxin  Judith Harris  NON-FICTION    CRIME
   index                 title           author    genre subgenre
0     88  unable unconsignable  Philip Bergevin  FICTION  FANTASY
   index         title        author    genre subgenre
0    103  resinol bede  Betty Jensen  FICTION   SCI-FI
   index               title          author    genre subgenre
0    140  ectogenic relented  Alison Coffman  FICTION  MYSTERY
   index                    title        author    genre subgenre
0     86  slateful superfinancing  Ruby Fortson  FICTION    CRIME
   index              title        author    genre subgenre
0    110  crumbers naphtali  Leland Miles  FICTION  MYSTERY
   index              title             author        genre   subgenre
0    107  woon ballyragging  Michael Velasquez  NON-FICTION  REFERENCE
   index                 title        author    genre subgenre
0    109  springworm thirsting  German Derck  FICTION   SCI-FI
   index                        title           author        genre subgenre
0      9  dithionic semimicrochemical  Michael Grisham  NON-FICTION    CRIME
   index           title           author        genre   subgenre
0    173  snitch grooper  Stephanie Loder  NON-FICTION  REFERENCE
   index                  title       author    genre subgenre
0     85  perityphlic sclerotic  John Vargas  FICTION   HORROR
   index                 title        author        genre subgenre
0    193  muscicolous menehune  Laura Taylor  NON-FICTION   TRAVEL
   index                    title        author        genre   subgenre
0     95  madrassah sclerectomies  Alan Conyers  NON-FICTION  REFERENCE
   index                  title        author        genre   subgenre
0     96  cephalodiscida toryfy  Carol Guzman  NON-FICTION  SELF-HELP
   index                  title      author        genre subgenre
0     93  coxalgia unlikelihood  Janet Rose  NON-FICTION  COOKING
   index                  title          author    genre subgenre
0    171  kinoplasmic liodermia  Thaddeus Scott  FICTION  FANTASY
   index                       title       author    genre subgenre
0     42  repentantly polyphonically  Sylvia Reid  FICTION  ROMANCE
   index               title          author        genre subgenre
0    152  karroo superstrain  Thomas Christy  NON-FICTION    CRIME
   index           title           author        genre   subgenre
0    173  snitch grooper  Stephanie Loder  NON-FICTION  REFERENCE
   index             title          author        genre   subgenre
0     74  querl prepensely  Keith Perryman  NON-FICTION  BIOGRAPHY
   index                title       author        genre   subgenre
0     56  kerrite schismatize  Jean Bigler  NON-FICTION  REFERENCE
   index                       title       author    genre subgenre
0     42  repentantly polyphonically  Sylvia Reid  FICTION  ROMANCE
   index                      title             author        genre   subgenre
0     47  nordenskioldine pedalling  Helena Monteleone  NON-FICTION  BIOGRAPHY
   index                            title     author        genre subgenre
0    133  pseudoceratites intramembranous  Tony Lane  NON-FICTION  HISTORY
   index               title          author        genre subgenre
0    194  simbil alcoholysis  Curt Hardebeck  NON-FICTION    CRIME
   index                   title         author    genre subgenre
0     31  restraightening fusing  John Peterson  FICTION   SCI-FI
   index                     title            author        genre subgenre
0    159  primevalism contrastment  Sherri Altmiller  NON-FICTION   TRAVEL
   index                       title        author        genre   subgenre
0     58  redivulge tenontomyoplasty  Cody Kamerer  NON-FICTION  REFERENCE
   index                 title        author        genre subgenre
0     11  adjoined archprimate  Randy Jacoby  NON-FICTION    CRIME
   index                    title        author    genre subgenre
0     86  slateful superfinancing  Ruby Fortson  FICTION    CRIME
   index             title       author    genre   subgenre
0    137  wullcat isoprene  Casey Ortiz  FICTION  ADVENTURE
   index                      title         author    genre subgenre
0      6  dissemblers bluestockings  Dino Schwalbe  FICTION   HORROR
   index                    title          author        genre   subgenre
0    104  structures graverobbing  David Hartmann  NON-FICTION  REFERENCE
   index           title         author    genre subgenre
0      3  unremote fifth  Dorothea King  FICTION   HORROR
   index               title         author    genre subgenre
0    197  spoilages sanglier  Shelley Smith  FICTION  HISTORY
   index                 title             author    genre   subgenre
0    131  nonhunting hoarstone  Gwendolyn Pollard  FICTION  ADVENTURE
   index               title         author    genre   subgenre
0     91  grapsidae salpians  Estelle Roche  FICTION  ADVENTURE
   index                    title        author        genre   subgenre
0     95  madrassah sclerectomies  Alan Conyers  NON-FICTION  REFERENCE
   index             title       author    genre subgenre
0    119  riverway slunken  Thomas Park  FICTION  MYSTERY
   index                            title        author    genre subgenre
0    141  ultranationalist uneffusiveness  Sheri Miller  FICTION  MYSTERY
   index                  title             author    genre subgenre
0    190  tesserarian chilidium  Gertrude Bradshaw  FICTION  HISTORY
   index             title        author        genre   subgenre
0    167  aptly zygotomere  Robert Rados  NON-FICTION  BIOGRAPHY
   index                       title       author    genre   subgenre
0    153  featishness radiostrontium  Kay Rushing  FICTION  ADVENTURE
   index                   title         author    genre subgenre
0    174  yeshiva symmetrization  Richard Fouse  FICTION  ROMANCE
   index                title            author    genre subgenre
0     62  saronide forficated  Rosetta Mitchell  FICTION   HORROR
   index                title         author        genre   subgenre
0     28  explicative gladded  Leslie Wisner  NON-FICTION  REFERENCE
   index                  title            author        genre   subgenre
0     21  mystified oxalonitril  Joshua Daugherty  NON-FICTION  BIOGRAPHY
   index                 title            author        genre subgenre
0     36  diazonium chamaerops  Carolyn Sullivan  NON-FICTION  HISTORY
   index                     title          author    genre subgenre
0    188  diagrammed noncoincident  Sherry Trotter  FICTION   SCI-FI
   index                           title          author    genre   subgenre
0     79  phylonepionic malappropriation  Catherine Cray  FICTION  ADVENTURE
   index                   title         author    genre subgenre
0    174  yeshiva symmetrization  Richard Fouse  FICTION  ROMANCE
   index                    title       author    genre subgenre
0    126  protandrism multisector  Daniel Lacy  FICTION    CRIME
   index                     title         author        genre   subgenre
0     26  misthrow nonblamefulness  Reggie Browne  NON-FICTION  BIOGRAPHY
   index                  title     author    genre subgenre
0     22  speeders unremembered  Van Moore  FICTION  FANTASY
   index              title        author        genre subgenre
0    166  preallots jestful  Brenda Olsen  NON-FICTION  COOKING
   index             title        author        genre   subgenre
0    167  aptly zygotomere  Robert Rados  NON-FICTION  BIOGRAPHY
   index                       title           author    genre subgenre
0    144  monothelitic hysterocystic  Regina Griswell  FICTION   HORROR
   index                   title         author    genre subgenre
0    174  yeshiva symmetrization  Richard Fouse  FICTION  ROMANCE
   index                title        author        genre   subgenre
0     45  preobtain vaporific  Barry Greene  NON-FICTION  SELF-HELP

   index          title       author        genre subgenre
0    148  gluing gymsia  Julie Floyd  NON-FICTION  HISTORY
   index                  title       author    genre subgenre
0     85  perityphlic sclerotic  John Vargas  FICTION   HORROR
   index                title           author    genre subgenre
0    150  awardment fleabites  Lori Fitzgerald  FICTION  HISTORY
   index                          title        author    genre subgenre
0     82  protuberantness anfractuosity  Ana Champlin  FICTION    CRIME
   index             title        author        genre   subgenre
0    167  aptly zygotomere  Robert Rados  NON-FICTION  BIOGRAPHY
   index                  title             author    genre subgenre
0    190  tesserarian chilidium  Gertrude Bradshaw  FICTION  HISTORY
   index              title         author        genre subgenre
0     51  prunetol aquarius  Bobbi Chapman  NON-FICTION    CRIME
   index                 title             author    genre   subgenre
0    131  nonhunting hoarstone  Gwendolyn Pollard  FICTION  ADVENTURE
   index                   title      author    genre   subgenre
0     46  megillah interlocutrix  John Glass  FICTION  ADVENTURE
   index               title          author        genre subgenre
0    194  simbil alcoholysis  Curt Hardebeck  NON-FICTION    CRIME
   index              title         author    genre   subgenre
0    180  oleander unespied  Tommie Bright  FICTION  ADVENTURE
   index                          title         author        genre   subgenre
0    176  disenthralled disenthronement  William Omara  NON-FICTION  REFERENCE
   index           title        author        genre subgenre
0    145  mirkiest anour  Angela Brock  NON-FICTION  COOKING
   index                   title        author    genre   subgenre
0     27  poeticize equiprobably  Connie Erben  FICTION  ADVENTURE
   index          title        author        genre   subgenre
0     19  acolytus crud  Edward Price  NON-FICTION  BIOGRAPHY
   index           title           author        genre   subgenre
0    173  snitch grooper  Stephanie Loder  NON-FICTION  REFERENCE
   index            title       author        genre subgenre
0    151  tritonal canyon  Melvin Sims  NON-FICTION  HISTORY
   index              title        author        genre subgenre
0    166  preallots jestful  Brenda Olsen  NON-FICTION  COOKING
   index                            title        author    genre subgenre
0    141  ultranationalist uneffusiveness  Sheri Miller  FICTION  MYSTERY
   index                title             author    genre subgenre
0    113  aglucone misaccount  Betty Catanzarite  FICTION  MYSTERY
   index               title           author        genre subgenre
0    134  outspanning prizes  Susan Ballester  NON-FICTION    CRIME
   index           title          author        genre   subgenre
0     38  tythed ravison  Gerard Dicicco  NON-FICTION  SELF-HELP
   index                       title       author    genre subgenre
0     42  repentantly polyphonically  Sylvia Reid  FICTION  ROMANCE
   index                      title         author    genre subgenre
0      6  dissemblers bluestockings  Dino Schwalbe  FICTION   HORROR
   index                      title         author    genre subgenre
0      4  diamant quadrituberculate  Jesse Prevost  FICTION   SCI-FI
   index                    title          author        genre subgenre
0    121  xylographer examinative  Antonio Mincey  NON-FICTION  COOKING
   index                        title           author    genre subgenre
0    182  preenvironmental electrical  Angela Mccurley  FICTION  MYSTERY
   index                   title        author    genre subgenre
0    196  hippopotamuses bejewel  Mary Johnson  FICTION    CRIME
   index                        title           author    genre subgenre
0    182  preenvironmental electrical  Angela Mccurley  FICTION  MYSTERY
   index                    title       author        genre   subgenre
0      8  scolopendrelloid gabbai  Eloy Sexton  NON-FICTION  BIOGRAPHY
   index                     title            author    genre subgenre
0     57  paddlecock kilomegacycle  Barbara Griffith  FICTION    CRIME
   index           title        author        genre subgenre
0    145  mirkiest anour  Angela Brock  NON-FICTION  COOKING
   index                          title        author    genre subgenre
0     82  protuberantness anfractuosity  Ana Champlin  FICTION    CRIME
   index                   title        author    genre subgenre
0    196  hippopotamuses bejewel  Mary Johnson  FICTION    CRIME
   index                  title      author        genre subgenre
0     61  supraworld siphonaria  Jose Mills  NON-FICTION  HISTORY
   index                  title        author    genre subgenre
0     12  masterling declaiming  Donald White  FICTION    CRIME
   index             title       author    genre   subgenre
0    137  wullcat isoprene  Casey Ortiz  FICTION  ADVENTURE
   index                       title           author    genre subgenre
0     37  radicalized presupposition  Charles Johnson  FICTION  ROMANCE
   index                   title        author    genre subgenre
0    196  hippopotamuses bejewel  Mary Johnson  FICTION    CRIME
   index                title        author        genre   subgenre
0     45  preobtain vaporific  Barry Greene  NON-FICTION  SELF-HELP
   index                     title         author    genre subgenre
0    199  takahe preacknowledgment  Donald Thomas  FICTION  FANTASY
   index              title          author        genre subgenre
0    155  hexachord leverer  Robin Eitniear  NON-FICTION  HISTORY
   index                    title        author    genre subgenre
0     86  slateful superfinancing  Ruby Fortson  FICTION    CRIME
   index              title          author        genre   subgenre
0     35  mousehound rethaw  Michael Holmes  NON-FICTION  BIOGRAPHY
   index                    title              author        genre subgenre
0     48  pseudoneuroptera zoners  Jacqueline Schmidt  NON-FICTION    CRIME
   index                        title           author        genre subgenre
0      9  dithionic semimicrochemical  Michael Grisham  NON-FICTION    CRIME
   index                   title              author    genre subgenre
0    138  marginal publicization  Theodore Hernandez  FICTION  FANTASY
   index                       title           author    genre subgenre
0    144  monothelitic hysterocystic  Regina Griswell  FICTION   HORROR
   index              title        author        genre   subgenre
0    117  beamishly airline  Larry Porter  NON-FICTION  SELF-HELP
   index                 title        author        genre subgenre
0     11  adjoined archprimate  Randy Jacoby  NON-FICTION    CRIME
   index                  title        author    genre subgenre
0     12  masterling declaiming  Donald White  FICTION    CRIME
   index           title        author    genre subgenre
0     43  eably admiring  Rose Sorrels  FICTION   HORROR
   index                  title      author        genre subgenre
0     93  coxalgia unlikelihood  Janet Rose  NON-FICTION  COOKING
   index             title            author        genre   subgenre
0     34  cygninae balarao  Clarence Andrews  NON-FICTION  SELF-HELP
   index                   title         author        genre subgenre
0     90  filterableness echinus  Alice Sanchez  NON-FICTION  HISTORY
   index                       title      author        genre subgenre
0     77  disassembling exhaustively  Jeri Rolfe  NON-FICTION  COOKING
   index                    title       author        genre   subgenre
0      8  scolopendrelloid gabbai  Eloy Sexton  NON-FICTION  BIOGRAPHY
   index                title       author        genre   subgenre
0     56  kerrite schismatize  Jean Bigler  NON-FICTION  REFERENCE
   index                    title       author        genre   subgenre
0      8  scolopendrelloid gabbai  Eloy Sexton  NON-FICTION  BIOGRAPHY
   index           title           author        genre   subgenre
0    173  snitch grooper  Stephanie Loder  NON-FICTION  REFERENCE
   index               title         author    genre   subgenre
0     91  grapsidae salpians  Estelle Roche  FICTION  ADVENTURE
   index                 title         author        genre subgenre
0    175  unfurrowed tapayaxin  Judith Harris  NON-FICTION    CRIME
   index              title          author        genre subgenre
0    155  hexachord leverer  Robin Eitniear  NON-FICTION  HISTORY
   index            title          author        genre subgenre
0     25  undertub hoboed  Janice Knowles  NON-FICTION  COOKING
   index                 title          author    genre subgenre
0    162  magnetizable rigadon  April Williams  FICTION  ROMANCE
   index             title       author    genre subgenre
0    119  riverway slunken  Thomas Park  FICTION  MYSTERY
   index              title           author    genre subgenre
0      2  transversely genu  Alexandra Henry  FICTION   SCI-FI
   index              title           author    genre subgenre
0      2  transversely genu  Alexandra Henry  FICTION   SCI-FI
   index                    title            author    genre subgenre
0     80  overcorrupt docibleness  Raymond Anderson  FICTION   SCI-FI
   index                  title       author    genre subgenre
0     16  blastplate electorial  Derek Leroy  FICTION  HISTORY
   index                 title          author    genre subgenre
0     99  postmeridional aimed  Keith Anderson  FICTION    CRIME
   index                 title        author        genre subgenre
0    193  muscicolous menehune  Laura Taylor  NON-FICTION   TRAVEL
   index              title         author        genre subgenre
0      0  kansans radiology  Laura Goodall  NON-FICTION   TRAVEL
   index                  title           author        genre   subgenre
0    191  balanus thysanuriform  Stephanie Lynch  NON-FICTION  BIOGRAPHY
   index                     title            author    genre subgenre
0     57  paddlecock kilomegacycle  Barbara Griffith  FICTION    CRIME
   index               title          author    genre subgenre
0    140  ectogenic relented  Alison Coffman  FICTION  MYSTERY
   index                 title             author    genre   subgenre
0    131  nonhunting hoarstone  Gwendolyn Pollard  FICTION  ADVENTURE
   index                  title       author    genre subgenre
0     85  perityphlic sclerotic  John Vargas  FICTION   HORROR
   index           title        author        genre subgenre
0    145  mirkiest anour  Angela Brock  NON-FICTION  COOKING
   index                 title         author        genre subgenre
0    115  lipwork disagreeable  Herbert Rains  NON-FICTION  COOKING
   index                     title           author        genre   subgenre
0     24  saturnine monotonousness  Martina Vitullo  NON-FICTION  BIOGRAPHY
   index               title        author    genre subgenre
0     39  mucose undigestion  Trevor Ceron  FICTION    CRIME
   index                  title            author        genre subgenre
0     71  pillory squamomastoid  Michael Thompson  NON-FICTION  COOKING
   index            title          author        genre subgenre
0     25  undertub hoboed  Janice Knowles  NON-FICTION  COOKING
   index            title        author    genre subgenre
0    185  mealily cooboos  Claudio Cote  FICTION  FANTASY
   index                  title      author    genre subgenre
0     63  nonirrigated dampness  Debra Byrd  FICTION   HORROR
   index               title         author    genre subgenre
0    197  spoilages sanglier  Shelley Smith  FICTION  HISTORY
   index               title      author    genre subgenre
0    172  liking initiatress  Nancy Chan  FICTION    CRIME
   index          title     author    genre subgenre
0     84  playa heiress  Shawn Kim  FICTION  MYSTERY
   index               title       author        genre subgenre
0     78  cadmus gentianales  David Jones  NON-FICTION  COOKING
   index                   title         author    genre subgenre
0    127  amphibia xerophthalmic  William Lewin  FICTION  HISTORY
   index       title         author        genre subgenre
0    178  essays gld  Sherrill Haas  NON-FICTION   TRAVEL
   index            title            author    genre subgenre
0    192  dullness spydom  Christine Thomas  FICTION    CRIME
   index                  title      author    genre subgenre
0    114  unstablished frousier  Tim Lawson  FICTION   HORROR
   index              title           author        genre subgenre
0     81  dawdle interludes  Debra Vannorman  NON-FICTION  HISTORY
   index           title           author        genre   subgenre
0    173  snitch grooper  Stephanie Loder  NON-FICTION  REFERENCE
   index                 title        author        genre   subgenre
0    183  neonatology embowels  Eden Hinkson  NON-FICTION  BIOGRAPHY
   index                 title           author    genre subgenre
0     88  unable unconsignable  Philip Bergevin  FICTION  FANTASY
   index                    title         author        genre subgenre
0    102  anticyclolysis shattery  Jeremy Kasper  NON-FICTION    CRIME
   index              title         author        genre subgenre
0     51  prunetol aquarius  Bobbi Chapman  NON-FICTION    CRIME

   index               title          author        genre subgenre
0    194  simbil alcoholysis  Curt Hardebeck  NON-FICTION    CRIME
   index          title        author    genre subgenre
0     10  pompon decadi  James Justus  FICTION   HORROR
   index              title        author    genre subgenre
0    198  mashru lignocaine  Connie Brown  FICTION   SCI-FI
   index                       title           author    genre subgenre
0    143  siphonogama aposematically  Katherine Jones  FICTION  FANTASY
   index             title       author    genre subgenre
0    119  riverway slunken  Thomas Park  FICTION  MYSTERY
   index          title     author    genre subgenre
0     84  playa heiress  Shawn Kim  FICTION  MYSTERY
   index              title        author    genre subgenre
0    198  mashru lignocaine  Connie Brown  FICTION   SCI-FI
   index                  title             author    genre subgenre
0    190  tesserarian chilidium  Gertrude Bradshaw  FICTION  HISTORY
   index           title          author        genre   subgenre
0     38  tythed ravison  Gerard Dicicco  NON-FICTION  SELF-HELP
   index                 title      author    genre subgenre
0    108  magistracies forblow  Jon Lozano  FICTION   SCI-FI
   index                       title        author    genre subgenre
0     15  merrytrotter coconspirator  Robert Davis  FICTION  ROMANCE
   index           title        author    genre subgenre
0     70  joyce selfcide  Calvin Coury  FICTION  HISTORY
   index                   title         author    genre subgenre
0     31  restraightening fusing  John Peterson  FICTION   SCI-FI
   index          title       author        genre subgenre
0    148  gluing gymsia  Julie Floyd  NON-FICTION  HISTORY
   index                    title        author        genre   subgenre
0     95  madrassah sclerectomies  Alan Conyers  NON-FICTION  REFERENCE
   index               title        author        genre subgenre
0     33  cassabanana meline  Robert Irwin  NON-FICTION   TRAVEL
   index              title     author        genre subgenre
0     53  pilage misbehaves  Tom Foote  NON-FICTION    CRIME
   index              title        author        genre   subgenre
0    101  megaloceros assay  James Staton  NON-FICTION  SELF-HELP
   index                            title        author    genre subgenre
0    141  ultranationalist uneffusiveness  Sheri Miller  FICTION  MYSTERY
   index             title              author    genre subgenre
0     66  fecche teniacide  Raymond Richardson  FICTION   HORROR
   index                     title          author    genre subgenre
0    188  diagrammed noncoincident  Sherry Trotter  FICTION   SCI-FI
   index                    title           author        genre   subgenre
0     75  settees overmultiplying  Jane Richardson  NON-FICTION  BIOGRAPHY
   index              title           author        genre subgenre
0     81  dawdle interludes  Debra Vannorman  NON-FICTION  HISTORY
   index              title        author    genre subgenre
0    118  candollea poodler  Donna Mayhew  FICTION  HISTORY
   index             title        author        genre   subgenre
0    167  aptly zygotomere  Robert Rados  NON-FICTION  BIOGRAPHY
   index                 title         author        genre subgenre
0    175  unfurrowed tapayaxin  Judith Harris  NON-FICTION    CRIME
   index                      title            author    genre subgenre
0    179  cyanophycin supervastness  Natalie Micciche  FICTION  HISTORY
   index                           title          author    genre   subgenre
0     79  phylonepionic malappropriation  Catherine Cray  FICTION  ADVENTURE
   index                   title         author    genre subgenre
0     31  restraightening fusing  John Peterson  FICTION   SCI-FI

In [5]:
print(display(df_copies))

     unquie                           title            author          branch
0      1337           unstablished frousier        Tim Lawson         Reading
1      1338           unstablished frousier        Tim Lawson         Reading
2      1339           unstablished frousier        Tim Lawson         Reading
3      1340           unstablished frousier        Tim Lawson         Reading
4      1341           unstablished frousier        Tim Lawson         Reading
...     ...                             ...               ...             ...
1072   2409                aptly zygotomere      Robert Rados      Portsmouth
1073   2410            unfurrowed tapayaxin     Judith Harris           Leeds
1074   2411       cyanophycin supervastness  Natalie Micciche      Manchester
1075   2412  phylonepionic malappropriation    Catherine Cray       Liverpool
1076   2413          restraightening fusing     John Peterson  Stoke-on-Trent

[1077 rows x 4 columns]

None

In [6]:
# loans
startframe = pd.Timestamp(year = 2022,  month = 11, day = 20,tz = 'GMT') 

endframe = pd.Timestamp(year = 2023,  month = 2, day = 20,tz = 'GMT') 

df_loans = pd.DataFrame(columns = ["uid","ref_to_copy_id","custid","startdate","enddate"])

for p in range(len(df_copies)):
    startlocal = startframe
    
    while(startlocal < endframe):
        endlocal = startlocal + timedelta(days=random.randint(2,31))
        
        df_temp = df_cust.sample()
        df_temp = df_temp.reset_index()
        custid = df_temp.loc[0,"uid"]

        df_len = len(df_loans)
        df_loans.loc[df_len,"uid"] = str("loan_"+str(df_len*2))
        df_loans.loc[df_len,"ref_to_copy_id"] = df_copies.loc[p,"unquie"]
        df_loans.loc[df_len,"custid"] = custid
        df_loans.loc[df_len,"startdate"] = startlocal.date()
        df_loans.loc[df_len,"enddate"] = endlocal.date()
        
        startlocal = endlocal+ timedelta(days=random.randint(12,50))

In [7]:
print(display(df_loans))

            uid ref_to_copy_id custid   startdate     enddate
0        loan_0           1337     86  2022-11-20  2022-11-30
1        loan_2           1337    199  2022-12-21  2022-12-23
2        loan_4           1337    111  2023-01-07  2023-02-05
3        loan_6           1338    130  2022-11-20  2022-12-16
4        loan_8           1338    145  2022-12-29  2023-01-25
...         ...            ...    ...         ...         ...
2607  loan_5214           2411     20  2023-01-22  2023-01-27
2608  loan_5216           2412    133  2022-11-20  2022-12-10
2609  loan_5218           2412     57  2023-01-22  2023-01-25
2610  loan_5220           2413    124  2022-11-20  2022-12-19
2611  loan_5222           2413     17  2023-01-19  2023-02-11

[2612 rows x 5 columns]

None

In [8]:
# holds

In [9]:
df_hold = pd.DataFrame(columns=["uidCust","title","author","queueNUM"])

y=0
for y in range(600):
    df_len = len(df_hold)
    
    df_temp_two = df_books.sample()
#     print(df_temp_two)
    df_temp_two = df_temp_two.reset_index()
    
    df_temp_three = df_cust.sample()
    df_temp_three = df_temp_three.reset_index()
    if (df_temp_three.loc[0,"uid"]) in (df_hold['uidCust'].unique()):
        print("skip")
    else:
        index = random.randint(0,len(df_books)-1)
        aut = df_books.loc[index,"author"]
        tit = df_books.loc[index,"title"]
        print(aut,tit)
        print("x",len(df_books.query("@aut in author and @tit in title")))
        
        if(len(df_books.query("(author == @aut) and (title ==  @tit)"))>0):
            df_single_book = df_hold.query("author == @aut and title ==  @tit")
            
            df_hold.loc[df_len,"title"] = tit
            df_hold.loc[df_len,"author"] = aut
            df_hold.loc[df_len,"uidCust"] = df_temp_three.loc[0,"uid"]

            order_so_far = len(df_single_book)

            if(order_so_far>0):
                print(order_so_far)
                df_hold.loc[df_len,"queueNUM"] = order_so_far + 1
            else:
                df_hold.loc[df_len,"queueNUM"] = 1


#             tut = df_hold.loc[df_len,"title"]
#             aut = df_hold.loc[df_len,"author"]
#             df_qur = df_books.query("@tut in title and @aut in author")
# #             print("is in the thingy" ,df_qur)

Laura Goodall kansans radiology
x 1
Janice Knowles undertub hoboed
x 1
Rosetta Mitchell saronide forficated
x 1
Rose Sorrels eably admiring
x 1
John Glass megillah interlocutrix
x 1
Mary Johnson hippopotamuses bejewel
x 1
Carolyn Sullivan diazonium chamaerops
x 1
Rhonda Lones sugarhouse megaseismic
x 1
Michael King undreadfully microsthenes
x 1
skip
Keith Anderson postmeridional aimed
x 1
Robert Rados aptly zygotomere
x 1
Carol Guzman cephalodiscida toryfy
x 1
Dino Schwalbe dissemblers bluestockings
x 1
William Miller chancefully crayonist
x 1
Julie Floyd gluing gymsia
x 1
Trevor Ceron mucose undigestion
x 1
Jean Bigler kerrite schismatize
x 1
Eddie Strzelecki nonreticently lindsay
x 1
Raymond Richardson fecche teniacide
x 1
Thomas Christy karroo superstrain
x 1
Gwendolyn Pollard nonhunting hoarstone
x 1
Laura Goodall kansans radiology
x 1
1
Leslie Wisner explicative gladded
x 1
Calvin Coury joyce selfcide
x 1
Allan Slater overseasoned employee
x 1
Jean Bigler kerrite schismatize
x 1
1
Tim Kindle hyperparathyroidism pilate
x 1
Eden Hinkson neonatology embowels
x 1
Casey Ortiz wullcat isoprene
x 1
Sherry Trotter diagrammed noncoincident
x 1
Glenda French pearlfish irrupted
x 1
Ruby Fortson slateful superfinancing
x 1
Stephanie Lynch balanus thysanuriform
x 1
Leland Miles crumbers naphtali
x 1
skip
Casey Ortiz wullcat isoprene
x 1
1
skip
Michael Holmes mousehound rethaw
x 1
Sue Seiler scranky semitones
x 1
Jon Lozano magistracies forblow
x 1
German Derck springworm thirsting
x 1
Inez Jackson cinnamyl copious
x 1
Joann Glud relentless unpersecutive
x 1
William Omara disenthralled disenthronement
x 1
George Grubaugh nonunification trilobated
x 1
Donald Thomas takahe preacknowledgment
x 1
Michael Thompson pillory squamomastoid
x 1
Rachel Johnson histophysiologic asuri
x 1
Estelle Roche grapsidae salpians
x 1
skip
skip
Dawn Lambdin cropsick hoggaster
x 1
Donna Mayhew candollea poodler
x 1
skip
Michael Holmes mousehound rethaw
x 1
1
Angela Brock mirkiest anour
x 1
Trevor Ceron mucose undigestion
x 1
1
Charles Johnson radicalized presupposition
x 1
Connie Brown mashru lignocaine
x 1
Robert Davis merrytrotter coconspirator
x 1
Carolyn Sullivan diazonium chamaerops
x 1
1
Shelley Smith spoilages sanglier
x 1
skip
Allan Slater overseasoned employee
x 1
1
Eden Hinkson neonatology embowels
x 1
1
skip
Michael Velasquez woon ballyragging
x 1
skip
skip
skip
Casey Ortiz wullcat isoprene
x 1
2
skip
skip
Nancy Callender uncurbed hrs
x 1
John Waite multiflagellate inadulterate
x 1
Sherry Trotter diagrammed noncoincident
x 1
1
Rosa Montville dizain taperness
x 1
skip
Reggie Browne misthrow nonblamefulness
x 1
skip
Jeremy Kasper anticyclolysis shattery
x 1
Connie Brown mashru lignocaine
x 1
1
Eloy Sexton scolopendrelloid gabbai
x 1
Rebecca Christner footpaddery haemic
x 1
Angela Brock mirkiest anour
x 1
1
Helen Weis notional unblocking
x 1
Tommie Bright oleander unespied
x 1
skip
skip
Leland Miles crumbers naphtali
x 1
1
skip
skip
Thomas Christy karroo superstrain
x 1
1
Reggie Browne misthrow nonblamefulness
x 1
1
skip
Clarence Andrews cygninae balarao
x 1
Stephanie Loder snitch grooper
x 1
Barbara Griffith paddlecock kilomegacycle
x 1
Laura Goodall kansans radiology
x 1
2
Shelley Smith spoilages sanglier
x 1
1
Dawn Lambdin cropsick hoggaster
x 1
1
skip
Robert Davis merrytrotter coconspirator
x 1
1
skip
skip
Shirley Stinnett uplit proprietory
x 1
Katie Gunn anserin repealability
x 1
skip
Claudio Cote mealily cooboos
x 1
William Miller chancefully crayonist
x 1
1
Jonathan Peck beefcake gonococcus
x 1
Nancy Pasch silhouettograph semiflexure
x 1
Eddie Strzelecki nonreticently lindsay
x 1
1
Jose Mills supraworld siphonaria
x 1
skip
Tommie Bright oleander unespied
x 1
1
Donald White masterling declaiming
x 1
Janice Macdonald smallen lilacthroat
x 1
skip
Robin Eitniear hexachord leverer
x 1
Glenda French pearlfish irrupted
x 1
1
Betty Catanzarite aglucone misaccount
x 1
Betty Catanzarite aglucone misaccount
x 1
1
Richard Fouse yeshiva symmetrization
x 1
skip
skip
Philip Bergevin unable unconsignable
x 1
skip
Antonio Santiago misguesses jackeen
x 1
skip
skip
Linda Spencer embeddable jotisaru
x 1
Leslie Wisner explicative gladded
x 1
1
Janet Rose coxalgia unlikelihood
x 1
Laura Taylor muscicolous menehune
x 1
James Staton megaloceros assay
x 1
skip
Patricia Duffin unarousable inequicostate
x 1
skip
skip
skip
skip
skip
skip
Michael Velasquez woon ballyragging
x 1
1
Judith Harris unfurrowed tapayaxin
x 1
Kay Rushing featishness radiostrontium
x 1
skip
skip
skip
Rachel Johnson histophysiologic asuri
x 1
1
Angela Brock mirkiest anour
x 1
2
Thomas Park riverway slunken
x 1
Angela Brock mirkiest anour
x 1
3
skip
Charles Johnson radicalized presupposition
x 1
1
skip
skip
Janice Macdonald smallen lilacthroat
x 1
1
skip
skip
skip
Ida Wheeler filthier original
x 1
skip
skip
Raymond Anderson overcorrupt docibleness
x 1
Janice Knowles undertub hoboed
x 1
1
Peter George expression ayubite
x 1
skip
Martina Vitullo saturnine monotonousness
x 1
skip
Helena Monteleone nordenskioldine pedalling
x 1
skip
skip
skip
skip
skip
Joyce Tanner prehistorical clivias
x 1
Rosetta Mitchell saronide forficated
x 1
1
skip
skip
skip
Jane Richardson settees overmultiplying
x 1
skip
skip
Stephanie Loder snitch grooper
x 1
1
skip
skip
Alison Coffman ectogenic relented
x 1
skip
skip
skip
skip
Luke Blodgett bookmate spiderier
x 1
skip
Janet Rose coxalgia unlikelihood
x 1
1
Jean Bigler kerrite schismatize
x 1
2
skip
skip
Randy Jacoby adjoined archprimate
x 1
Cody Kamerer redivulge tenontomyoplasty
x 1
skip
James Jones lachrymae dunged
x 1
skip
Thaddeus Scott kinoplasmic liodermia
x 1
skip
skip
skip
skip
skip
skip
James Staton megaloceros assay
x 1
1
skip
skip
Alonzo Bench ectomesoblast distune
x 1
skip
skip
skip
skip
skip
skip
skip
John Vargas perityphlic sclerotic
x 1
skip
Jeremy Kasper anticyclolysis shattery
x 1
1
Joshua Daugherty mystified oxalonitril
x 1
skip
skip
Gladys Fischer eucosmid missteered
x 1
Joshua Daugherty mystified oxalonitril
x 1
1
skip
skip
Margot Drake myxogastres interchain
x 1
skip
skip
skip
Alan Conyers madrassah sclerectomies
x 1
Gwendolyn Pollard nonhunting hoarstone
x 1
1
skip
James Jones lachrymae dunged
x 1
1
skip
skip
skip
skip
skip
skip
Robert Rados aptly zygotomere
x 1
1
David Powell rededicated intrapericardiac
x 1
skip
skip
skip
skip
skip
skip
skip
Trevor Ceron mucose undigestion
x 1
2
skip
skip
skip
skip
skip
skip
skip
Theodore Hernandez marginal publicization
x 1
skip
skip
Sherryl Holloway blitzkrieg erses
x 1
skip
Thomas Christy karroo superstrain
x 1
2
skip
skip
skip
skip
Angela Brock mirkiest anour
x 1
4
skip
skip
Ana Champlin protuberantness anfractuosity
x 1
Ruby Fortson slateful superfinancing
x 1
1
skip
Bobbi Chapman prunetol aquarius
x 1
William Omara disenthralled disenthronement
x 1
1
Edward Price acolytus crud
x 1
skip
skip
skip
skip
skip
skip
Betty Jensen resinol bede
x 1
skip
Tim Kindle hyperparathyroidism pilate
x 1
1
Robert Munson plateasm cryable
x 1
Theodore Hernandez marginal publicization
x 1
1
Christine Thomas dullness spydom
x 1
skip
skip
skip
skip
skip
Michael Thompson pillory squamomastoid
x 1
1
skip
skip
skip
skip
skip
skip
skip
skip
Robin Eitniear hexachord leverer
x 1
1
skip
skip
skip
skip
skip
skip
skip
skip
skip
Tom Foote pilage misbehaves
x 1
Leslie Wisner explicative gladded
x 1
2
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Dorothea King unremote fifth
x 1
skip
Calvin Coury joyce selfcide
x 1
1
skip
skip
skip
skip
skip
skip
skip
skip
Catherine Cray phylonepionic malappropriation
x 1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Claudio Cote mealily cooboos
x 1
1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Tim Kindle hyperparathyroidism pilate
x 1
2
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Alexandra Henry transversely genu
x 1
Martin Priest missable propheticality
x 1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Harold Giard enframes burrhead
x 1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Martina Vitullo saturnine monotonousness
x 1
1
skip
skip
skip
skip
skip
Raymond Richardson fecche teniacide
x 1
1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Ida Wheeler filthier original
x 1

1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Dianne Clay splashwing antitheistic
x 1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
George Grubaugh nonunification trilobated
x 1
1
skip
Eloy Sexton scolopendrelloid gabbai
x 1
1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Eddie Strzelecki nonreticently lindsay
x 1
2
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Edward Price acolytus crud
x 1
1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Eddie Strzelecki nonreticently lindsay
x 1
3
skip
Rosa Montville dizain taperness
x 1
1
skip
skip
skip
skip
skip
Marcus Pritchard fecklessly beachboys
x 1
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
Raymond Richardson fecche teniacide
x 1
2
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip

In [11]:
# returns
# no longer each only borrowed at same time shoudl fix

df_returns = pd.DataFrame(columns=["loanID","date"])

for u in range(len(df_loans)):
    df_len = len(df_returns)
    
    if(u < len(df_loans) -1):
        if(df_loans.loc[u+1,"ref_to_copy_id"] == df_loans.loc[u,"ref_to_copy_id"]):
            returndateMAX = df_loans.loc[u+1,"startdate"]
        else:
            returndateMAX = df_loans.loc[u,"startdate"]+timedelta(days=100)
    else:
        returndateMAX = df_loans.loc[u,"startdate"]+ timedelta(days=100)
        
    returndateMIN = df_loans.loc[u,"startdate"]
    
    df_returns.loc[df_len,"loanID"] = df_loans.loc[u,"uid"]
    df_returns.loc[df_len,"date"] = df_loans.loc[u,"startdate"] + timedelta(days=random.randint(1,17))
    
    df_returns = df_returns.drop_duplicates()

In [12]:
display(df_returns)

         loanID        date
0        loan_0  2022-11-22
1        loan_2  2023-01-06
2        loan_4  2023-01-12
3        loan_6  2022-12-06
4        loan_8  2023-01-04
...         ...         ...
2607  loan_5214  2023-01-30
2608  loan_5216  2022-11-27
2609  loan_5218  2023-01-24
2610  loan_5220  2022-11-24
2611  loan_5222  2023-02-03

[2612 rows x 2 columns]

In [13]:
# remember to add the cases i should be finding for each question

In [15]:
df_returns = df_returns.reset_index()

In [16]:
# creates the inserts for postgres

# INSERT INTO table_name(column1, column2, â€¦)
# VALUES (value1, value2, â€¦);
# df_books = pd.DataFrame(columns=["title","author","genre","subgenre"])

r = 0

cust_string = ""

for r in range(len(df_books)):
    insert = "INSERT INTO Books(title,author,genre,subgenre) VALUES(\""+df_books.loc[r,"title"]+"\",\""+(df_books.loc[r,"author"])+"\",\""+df_books.loc[r,"genre"]+"\",\""+df_books.loc[r,"subgenre"]+"\");"
    print(insert)
    cust_string = cust_string + insert
    
    
# df_cust = pd.DataFrame(columns = ["uid","name","branch"])
r = 0  
for r in range(len(df_cust)):
    insert = "INSERT INTO Customers(cust_id,name,branch) VALUES(\""+str(df_cust.loc[r,"uid"])+"\",\""+(df_cust.loc[r,"name"])+"\",\""+df_cust.loc[r,"branch"]+"\");"
    print(insert)
    cust_string = cust_string + insert
    

# df_cust = pd.DataFrame(columns = ["uid","name","branch"])
r = 0  
for r in range(len(df_copies)):
    insert = "INSERT INTO Copies(copy_id,title,author,branch) VALUES(\""+str(df_copies.loc[r,"unquie"])+"\",\""+(df_copies.loc[r,"title"])+"\",\""+df_copies.loc[r,"author"]+"\",\""+df_copies.loc[r,"branch"]+"\");"
    print(insert)
    cust_string = cust_string + insert
    
r = 0  
for r in range(len(df_loans)):
    insert = "INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES(\""+str(df_loans.loc[r,"uid"])+"\",\""+str((df_loans.loc[r,"ref_to_copy_id"]))+"\",\""+str(df_loans.loc[r,"custid"])+"\",\""+str(df_loans.loc[r,"startdate"])+"\",\""+str(df_loans.loc[r,"enddate"])+"\");"
    print(insert)
    cust_string = cust_string + insert
    
r = 0  
for r in range(len(df_returns)):
    insert = "INSERT INTO Returns(loan,date) VALUES(\""+str(df_returns.loc[r,"loanID"])+"\",\""+str((df_returns.loc[r,"date"]))+"\");"
    print(insert)
    cust_string = cust_string + insert

# df_hold = pd.DataFrame(columns=["uidCust","title","author","queueNUM"])
r = 0  
for r in range(len(df_hold)):
    insert = "INSERT INTO Holds(customer,title,author,queue) VALUES(\""+str(df_hold.loc[r,"uidCust"])+"\",\""+str((df_hold.loc[r,"title"]))+"\",\""+str(df_hold.loc[r,"author"])+"\","+str(df_hold.loc[r,"queueNUM"])+");"
    print(insert)
    cust_string = cust_string + insert

INSERT INTO Books(title,author,genre,subgenre) VALUES("kansans radiology","Laura Goodall","NON-FICTION","TRAVEL");
INSERT INTO Books(title,author,genre,subgenre) VALUES("dilemmas unerected","Alan Ritter","NON-FICTION","TRAVEL");
INSERT INTO Books(title,author,genre,subgenre) VALUES("transversely genu","Alexandra Henry","FICTION","SCI-FI");
INSERT INTO Books(title,author,genre,subgenre) VALUES("unremote fifth","Dorothea King","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("diamant quadrituberculate","Jesse Prevost","FICTION","SCI-FI");
INSERT INTO Books(title,author,genre,subgenre) VALUES("laos nonbarbaric","Matthew Matta","NON-FICTION","TRAVEL");
INSERT INTO Books(title,author,genre,subgenre) VALUES("dissemblers bluestockings","Dino Schwalbe","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("piaroan foolhardiness","Joshua Elliott","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("scolopendrelloid gabbai","Eloy Sexton","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("dithionic semimicrochemical","Michael Grisham","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("pompon decadi","James Justus","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("adjoined archprimate","Randy Jacoby","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("masterling declaiming","Donald White","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("silhouettograph semiflexure","Nancy Pasch","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("eucosmid missteered","Gladys Fischer","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("merrytrotter coconspirator","Robert Davis","FICTION","ROMANCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("blastplate electorial","Derek Leroy","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("dizain taperness","Rosa Montville","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("embeddable jotisaru","Linda Spencer","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("acolytus crud","Edward Price","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("superindustriousness dealership","Alexis Wright","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("mystified oxalonitril","Joshua Daugherty","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("speeders unremembered","Van Moore","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("optimised tinbergen","Lynn Miller","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("saturnine monotonousness","Martina Vitullo","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("undertub hoboed","Janice Knowles","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("misthrow nonblamefulness","Reggie Browne","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("poeticize equiprobably","Connie Erben","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("explicative gladded","Leslie Wisner","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("nonreticently lindsay","Eddie Strzelecki","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("mascons akal","Mary Thompson","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("restraightening fusing","John Peterson","FICTION","SCI-FI");
INSERT INTO Books(title,author,genre,subgenre) VALUES("myxogastres interchain","Margot Drake","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("cassabanana meline","Robert Irwin","NON-FICTION","TRAVEL");
INSERT INTO Books(title,author,genre,subgenre) VALUES("cygninae balarao","Clarence Andrews","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("mousehound rethaw","Michael Holmes","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("diazonium chamaerops","Carolyn Sullivan","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("radicalized presupposition","Charles Johnson","FICTION","ROMANCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("tythed ravison","Gerard Dicicco","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("mucose undigestion","Trevor Ceron","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("cavicorn nm","William Lambrecht","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("smallen lilacthroat","Janice Macdonald","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("repentantly polyphonically","Sylvia Reid","FICTION","ROMANCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("eably admiring","Rose Sorrels","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("cinnamyl copious","Inez Jackson","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("preobtain vaporific","Barry Greene","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("megillah interlocutrix","John Glass","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("nordenskioldine pedalling","Helena Monteleone","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("pseudoneuroptera zoners","Jacqueline Schmidt","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("expression ayubite","Peter George","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("pluviometrical sutoria","Steven Baker","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("prunetol aquarius","Bobbi Chapman","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("gooier snuffed","Maryjo Nowlin","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("pilage misbehaves","Tom Foote","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("hardbound slynesses","James Dixon","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("notional unblocking","Helen Weis","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("kerrite schismatize","Jean Bigler","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("paddlecock kilomegacycle","Barbara Griffith","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("redivulge tenontomyoplasty","Cody Kamerer","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("vafrous chapelgoer","Frank Hoffmann","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("whitewashed forfeiture","Erick Newkirk","NON-FICTION","TRAVEL");
INSERT INTO Books(title,author,genre,subgenre) VALUES("supraworld siphonaria","Jose Mills","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("saronide forficated","Rosetta Mitchell","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("nonirrigated dampness","Debra Byrd","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("enframes burrhead","Harold Giard","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("congeeing undesirability","Kristy Luttrell","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("fecche teniacide","Raymond Richardson","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("unarousable inequicostate","Patricia Duffin","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("beefcake gonococcus","Jonathan Peck","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("multiflagellate inadulterate","John Waite","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("joyce selfcide","Calvin Coury","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("pillory squamomastoid","Michael Thompson","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("dittoed anematizing","Rocky Garcia","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("pocketbook semionotus","Margaret Chandler","FICTION","SCI-FI");
INSERT INTO Books(title,author,genre,subgenre) VALUES("querl prepensely","Keith Perryman","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("settees overmultiplying","Jane Richardson","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("chancefully crayonist","William Miller","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("disassembling exhaustively","Jeri Rolfe","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("cadmus gentianales","David Jones","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("phylonepionic malappropriation","Catherine Cray","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("overcorrupt docibleness","Raymond Anderson","FICTION","SCI-FI");
INSERT INTO Books(title,author,genre,subgenre) VALUES("dawdle interludes","Debra Vannorman","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("protuberantness anfractuosity","Ana Champlin","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("durgah deckel","Rose Nash","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("playa heiress","Shawn Kim","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("perityphlic sclerotic","John Vargas","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("slateful superfinancing","Ruby Fortson","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("uplit proprietory","Shirley Stinnett","FICTION","ROMANCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("unable unconsignable","Philip Bergevin","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("histophysiologic asuri","Rachel Johnson","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("filterableness echinus","Alice Sanchez","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("grapsidae salpians","Estelle Roche","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("bookmate spiderier","Luke Blodgett","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("coxalgia unlikelihood","Janet Rose","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("notifiable ephphatha","Juanita Burke","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("madrassah sclerectomies","Alan Conyers","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("cephalodiscida toryfy","Carol Guzman","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("splashwing antitheistic","Dianne Clay","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("lasts catechist","Brian Smith","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("postmeridional aimed","Keith Anderson","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("lachrymae dunged","James Jones","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("megaloceros assay","James Staton","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("anticyclolysis shattery","Jeremy Kasper","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("resinol bede","Betty Jensen","FICTION","SCI-FI");
INSERT INTO Books(title,author,genre,subgenre) VALUES("structures graverobbing","David Hartmann","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("scranky semitones","Sue Seiler","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("pearlfish irrupted","Glenda French","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("woon ballyragging","Michael Velasquez","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("magistracies forblow","Jon Lozano","FICTION","SCI-FI");
INSERT INTO Books(title,author,genre,subgenre) VALUES("springworm thirsting","German Derck","FICTION","SCI-FI");
INSERT INTO Books(title,author,genre,subgenre) VALUES("crumbers naphtali","Leland Miles","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("footpaddery haemic","Rebecca Christner","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("suppletively plopped","Patsy Wells","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("aglucone misaccount","Betty Catanzarite","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("unstablished frousier","Tim Lawson","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("lipwork disagreeable","Herbert Rains","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("bismosol fibrillous","Phillip Wascher","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("beamishly airline","Larry Porter","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("candollea poodler","Donna Mayhew","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("riverway slunken","Thomas Park","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("nonuniversally straticulation","Edward Norris","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("xylographer examinative","Antonio Mincey","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("sugarhouse megaseismic","Rhonda Lones","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("lira spenders","Teresa Ervin","NON-FICTION","TRAVEL");
INSERT INTO Books(title,author,genre,subgenre) VALUES("cropsick hoggaster","Dawn Lambdin","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("counterattestation percents","Brittany Robinson","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("protandrism multisector","Daniel Lacy","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("amphibia xerophthalmic","William Lewin","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("anamorphous undersward","Christopher Jones","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("hyperparathyroidism pilate","Tim Kindle","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("thoughtlet thiocyanide","Carlton Donnelly","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("nonhunting hoarstone","Gwendolyn Pollard","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("plutocrat spalt","Lauren Hopton","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("pseudoceratites intramembranous","Tony Lane","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("outspanning prizes","Susan Ballester","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("blitzkrieg erses","Sherryl Holloway","NON-FICTION","TRAVEL");
INSERT INTO Books(title,author,genre,subgenre) VALUES("oophytic lewdness","George Anderson","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("wullcat isoprene","Casey Ortiz","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("marginal publicization","Theodore Hernandez","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("undreadfully microsthenes","Michael King","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("ectogenic relented","Alison Coffman","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("ultranationalist uneffusiveness","Sheri Miller","FICTION","MYSTERY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("sosia chitlin","Richard Ragland","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("siphonogama aposematically","Katherine Jones","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("monothelitic hysterocystic","Regina Griswell","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("mirkiest anour","Angela Brock","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("druthers palaeographical","Patrick Manrique","NON-FICTION","REFERENCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("overseasoned employee","Allan Slater","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("gluing gymsia","Julie Floyd","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("anserin repealability","Katie Gunn","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("awardment fleabites","Lori Fitzgerald","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("tritonal canyon","Melvin Sims","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("karroo superstrain","Thomas Christy","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("featishness radiostrontium","Kay Rushing","FICTION","ADVENTURE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("filthier original","Ida Wheeler","FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("hexachord leverer","Robin Eitniear","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("dynastically proganosaur","Randell Pell","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("ectomesoblast distune","Alonzo Bench","NON-FICTION","CRIME");
INSERT INTO Books(title,author,genre,subgenre) VALUES("magmata cloudlessly","Lisa Grant","NON-FICTION","SELF-HELP");
INSERT INTO Books(title,author,genre,subgenre) VALUES("primevalism contrastment","Sherri Altmiller","NON-FICTION","TRAVEL");
INSERT INTO Books(title,author,genre,subgenre) VALUES("lucifugous piassaba","Anthony Jackson","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("fecklessly beachboys","Marcus Pritchard","FICTION","HORROR");
INSERT INTO Books(title,author,genre,subgenre) VALUES("magnetizable rigadon","April Williams","FICTION","ROMANCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("nonunification trilobated","George Grubaugh","FICTION","FANTASY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("percussionize elixirs","Sarah Delaney","NON-FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("rededicated intrapericardiac","David Powell","FICTION","HISTORY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("preallots jestful","Brenda Olsen","NON-FICTION","COOKING");
INSERT INTO Books(title,author,genre,subgenre) VALUES("aptly zygotomere","Robert Rados","NON-FICTION","BIOGRAPHY");
INSERT INTO Books(title,author,genre,subgenre) VALUES("bevvy upband","Jessica Menchaca","FICTION","ROMANCE");
INSERT INTO Books(title,author,genre,subgenre) VALUES("semiconservative madras","Donna Goodnight","NON-FICTION","HISTORY");

INSERT INTO Copies(copy_id,title,author,branch) VALUES("1839","cassabanana meline","Robert Irwin","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1840","cassabanana meline","Robert Irwin","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1841","cassabanana meline","Robert Irwin","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1842","cassabanana meline","Robert Irwin","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1843","cassabanana meline","Robert Irwin","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1844","cassabanana meline","Robert Irwin","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1845","laos nonbarbaric","Matthew Matta","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1846","thoughtlet thiocyanide","Carlton Donnelly","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1847","pocketbook semionotus","Margaret Chandler","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1848","ultranationalist uneffusiveness","Sheri Miller","Nottingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1849","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1850","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1851","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1852","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1853","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1854","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1855","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1856","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1857","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1858","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1859","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1860","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1861","takahe preacknowledgment","Donald Thomas","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1862","merrytrotter coconspirator","Robert Davis","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1863","missable propheticality","Martin Priest","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1864","joyce selfcide","Calvin Coury","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1865","durgah deckel","Rose Nash","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1866","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1867","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1868","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1869","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1870","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1871","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1872","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1873","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1874","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1875","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1876","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1877","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1878","unremote fifth","Dorothea King","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1879","congeeing undesirability","Kristy Luttrell","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1880","primevalism contrastment","Sherri Altmiller","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1881","dynastically proganosaur","Randell Pell","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1882","essays gld","Sherrill Haas","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1883","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1884","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1885","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1886","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1887","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1888","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1889","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1890","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1891","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1892","candollea poodler","Donna Mayhew","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1893","mirkiest anour","Angela Brock","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1894","plateasm cryable","Robert Munson","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1895","suppletively plopped","Patsy Wells","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1896","ectogenic relented","Alison Coffman","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1897","protandrism multisector","Daniel Lacy","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1898","protandrism multisector","Daniel Lacy","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1899","protandrism multisector","Daniel Lacy","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1900","protandrism multisector","Daniel Lacy","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1901","protandrism multisector","Daniel Lacy","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1902","protandrism multisector","Daniel Lacy","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1903","thoughtlet thiocyanide","Carlton Donnelly","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1904","muscicolous menehune","Laura Taylor","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1905","primevalism contrastment","Sherri Altmiller","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1906","uncurbed hrs","Nancy Callender","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1907","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1908","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1909","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1910","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1911","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1912","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1913","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1914","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1915","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1916","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1917","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1918","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1919","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1920","misguesses jackeen","Antonio Santiago","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1921","pillory squamomastoid","Michael Thompson","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1922","unfurrowed tapayaxin","Judith Harris","Nottingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1923","unable unconsignable","Philip Bergevin","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1924","resinol bede","Betty Jensen","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1925","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1926","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1927","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1928","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1929","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1930","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1931","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1932","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1933","ectogenic relented","Alison Coffman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1934","slateful superfinancing","Ruby Fortson","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1935","crumbers naphtali","Leland Miles","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1936","woon ballyragging","Michael Velasquez","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1937","springworm thirsting","German Derck","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1938","dithionic semimicrochemical","Michael Grisham","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1939","dithionic semimicrochemical","Michael Grisham","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1940","dithionic semimicrochemical","Michael Grisham","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1941","snitch grooper","Stephanie Loder","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1942","perityphlic sclerotic","John Vargas","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1943","muscicolous menehune","Laura Taylor","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1944","madrassah sclerectomies","Alan Conyers","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1945","cephalodiscida toryfy","Carol Guzman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1946","cephalodiscida toryfy","Carol Guzman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1947","cephalodiscida toryfy","Carol Guzman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1948","cephalodiscida toryfy","Carol Guzman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1949","coxalgia unlikelihood","Janet Rose","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1950","kinoplasmic liodermia","Thaddeus Scott","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1951","repentantly polyphonically","Sylvia Reid","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1952","karroo superstrain","Thomas Christy","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1953","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1954","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1955","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1956","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1957","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1958","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1959","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1960","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1961","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1962","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1963","snitch grooper","Stephanie Loder","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1964","querl prepensely","Keith Perryman","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1965","kerrite schismatize","Jean Bigler","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1966","repentantly polyphonically","Sylvia Reid","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1967","nordenskioldine pedalling","Helena Monteleone","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1968","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1969","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1970","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1971","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1972","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1973","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1974","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1975","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1976","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1977","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1978","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1979","pseudoceratites intramembranous","Tony Lane","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1980","simbil alcoholysis","Curt Hardebeck","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1981","restraightening fusing","John Peterson","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1982","primevalism contrastment","Sherri Altmiller","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1983","redivulge tenontomyoplasty","Cody Kamerer","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1984","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1985","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1986","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1987","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1988","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1989","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1990","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1991","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1992","adjoined archprimate","Randy Jacoby","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1993","slateful superfinancing","Ruby Fortson","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1994","wullcat isoprene","Casey Ortiz","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1995","dissemblers bluestockings","Dino Schwalbe","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1996","structures graverobbing","David Hartmann","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1997","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1998","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("1999","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2000","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2001","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2002","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2003","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2004","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2005","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2006","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2007","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2008","unremote fifth","Dorothea King","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2009","spoilages sanglier","Shelley Smith","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2010","nonhunting hoarstone","Gwendolyn Pollard","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2011","grapsidae salpians","Estelle Roche","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2012","madrassah sclerectomies","Alan Conyers","Birstall");

INSERT INTO Copies(copy_id,title,author,branch) VALUES("2081","preobtain vaporific","Barry Greene","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2082","gluing gymsia","Julie Floyd","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2083","perityphlic sclerotic","John Vargas","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2084","awardment fleabites","Lori Fitzgerald","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2085","protuberantness anfractuosity","Ana Champlin","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2086","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2087","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2088","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2089","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2090","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2091","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2092","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2093","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2094","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2095","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2096","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2097","aptly zygotomere","Robert Rados","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2098","tesserarian chilidium","Gertrude Bradshaw","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2099","prunetol aquarius","Bobbi Chapman","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2100","nonhunting hoarstone","Gwendolyn Pollard","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2101","megillah interlocutrix","John Glass","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2102","simbil alcoholysis","Curt Hardebeck","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2103","simbil alcoholysis","Curt Hardebeck","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2104","simbil alcoholysis","Curt Hardebeck","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2105","simbil alcoholysis","Curt Hardebeck","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2106","oleander unespied","Tommie Bright","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2107","disenthralled disenthronement","William Omara","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2108","mirkiest anour","Angela Brock","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2109","poeticize equiprobably","Connie Erben","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2110","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2111","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2112","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2113","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2114","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2115","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2116","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2117","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2118","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2119","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2120","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2121","acolytus crud","Edward Price","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2122","snitch grooper","Stephanie Loder","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2123","tritonal canyon","Melvin Sims","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2124","preallots jestful","Brenda Olsen","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2125","ultranationalist uneffusiveness","Sheri Miller","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2126","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2127","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2128","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2129","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2130","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2131","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2132","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2133","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2134","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2135","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2136","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2137","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2138","aglucone misaccount","Betty Catanzarite","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2139","outspanning prizes","Susan Ballester","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2140","tythed ravison","Gerard Dicicco","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2141","repentantly polyphonically","Sylvia Reid","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2142","dissemblers bluestockings","Dino Schwalbe","Nottingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2143","diamant quadrituberculate","Jesse Prevost","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2144","diamant quadrituberculate","Jesse Prevost","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2145","diamant quadrituberculate","Jesse Prevost","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2146","diamant quadrituberculate","Jesse Prevost","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2147","diamant quadrituberculate","Jesse Prevost","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2148","diamant quadrituberculate","Jesse Prevost","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2149","diamant quadrituberculate","Jesse Prevost","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2150","diamant quadrituberculate","Jesse Prevost","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2151","xylographer examinative","Antonio Mincey","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2152","preenvironmental electrical","Angela Mccurley","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2153","hippopotamuses bejewel","Mary Johnson","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2154","preenvironmental electrical","Angela Mccurley","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2155","scolopendrelloid gabbai","Eloy Sexton","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2156","scolopendrelloid gabbai","Eloy Sexton","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2157","scolopendrelloid gabbai","Eloy Sexton","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2158","paddlecock kilomegacycle","Barbara Griffith","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2159","mirkiest anour","Angela Brock","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2160","protuberantness anfractuosity","Ana Champlin","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2161","hippopotamuses bejewel","Mary Johnson","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2162","supraworld siphonaria","Jose Mills","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2163","supraworld siphonaria","Jose Mills","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2164","supraworld siphonaria","Jose Mills","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2165","supraworld siphonaria","Jose Mills","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2166","supraworld siphonaria","Jose Mills","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2167","supraworld siphonaria","Jose Mills","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2168","supraworld siphonaria","Jose Mills","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2169","masterling declaiming","Donald White","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2170","wullcat isoprene","Casey Ortiz","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2171","radicalized presupposition","Charles Johnson","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2172","hippopotamuses bejewel","Mary Johnson","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2173","preobtain vaporific","Barry Greene","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2174","preobtain vaporific","Barry Greene","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2175","preobtain vaporific","Barry Greene","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2176","preobtain vaporific","Barry Greene","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2177","preobtain vaporific","Barry Greene","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2178","takahe preacknowledgment","Donald Thomas","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2179","hexachord leverer","Robin Eitniear","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2180","slateful superfinancing","Ruby Fortson","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2181","mousehound rethaw","Michael Holmes","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2182","pseudoneuroptera zoners","Jacqueline Schmidt","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2183","pseudoneuroptera zoners","Jacqueline Schmidt","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2184","pseudoneuroptera zoners","Jacqueline Schmidt","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2185","dithionic semimicrochemical","Michael Grisham","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2186","marginal publicization","Theodore Hernandez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2187","monothelitic hysterocystic","Regina Griswell","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2188","beamishly airline","Larry Porter","Nottingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2189","adjoined archprimate","Randy Jacoby","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2190","adjoined archprimate","Randy Jacoby","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2191","adjoined archprimate","Randy Jacoby","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2192","adjoined archprimate","Randy Jacoby","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2193","masterling declaiming","Donald White","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2194","eably admiring","Rose Sorrels","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2195","coxalgia unlikelihood","Janet Rose","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2196","cygninae balarao","Clarence Andrews","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2197","filterableness echinus","Alice Sanchez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2198","filterableness echinus","Alice Sanchez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2199","filterableness echinus","Alice Sanchez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2200","filterableness echinus","Alice Sanchez","Reading");

INSERT INTO Copies(copy_id,title,author,branch) VALUES("2201","filterableness echinus","Alice Sanchez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2202","filterableness echinus","Alice Sanchez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2203","filterableness echinus","Alice Sanchez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2204","filterableness echinus","Alice Sanchez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2205","filterableness echinus","Alice Sanchez","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2206","disassembling exhaustively","Jeri Rolfe","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2207","scolopendrelloid gabbai","Eloy Sexton","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2208","kerrite schismatize","Jean Bigler","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2209","scolopendrelloid gabbai","Eloy Sexton","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2210","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2211","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2212","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2213","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2214","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2215","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2216","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2217","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2218","snitch grooper","Stephanie Loder","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2219","grapsidae salpians","Estelle Roche","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2220","unfurrowed tapayaxin","Judith Harris","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2221","hexachord leverer","Robin Eitniear","Sheffield");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2222","undertub hoboed","Janice Knowles","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2223","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2224","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2225","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2226","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2227","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2228","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2229","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2230","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2231","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2232","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2233","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2234","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2235","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2236","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2237","magnetizable rigadon","April Williams","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2238","riverway slunken","Thomas Park","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2239","transversely genu","Alexandra Henry","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2240","transversely genu","Alexandra Henry","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2241","overcorrupt docibleness","Raymond Anderson","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2242","blastplate electorial","Derek Leroy","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2243","blastplate electorial","Derek Leroy","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2244","blastplate electorial","Derek Leroy","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2245","blastplate electorial","Derek Leroy","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2246","blastplate electorial","Derek Leroy","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2247","blastplate electorial","Derek Leroy","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2248","blastplate electorial","Derek Leroy","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2249","postmeridional aimed","Keith Anderson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2250","muscicolous menehune","Laura Taylor","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2251","kansans radiology","Laura Goodall","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2252","balanus thysanuriform","Stephanie Lynch","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2253","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2254","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2255","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2256","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2257","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2258","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2259","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2260","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2261","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2262","paddlecock kilomegacycle","Barbara Griffith","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2263","ectogenic relented","Alison Coffman","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2264","nonhunting hoarstone","Gwendolyn Pollard","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2265","perityphlic sclerotic","John Vargas","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2266","mirkiest anour","Angela Brock","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2267","lipwork disagreeable","Herbert Rains","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2268","lipwork disagreeable","Herbert Rains","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2269","lipwork disagreeable","Herbert Rains","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2270","lipwork disagreeable","Herbert Rains","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2271","lipwork disagreeable","Herbert Rains","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2272","saturnine monotonousness","Martina Vitullo","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2273","mucose undigestion","Trevor Ceron","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2274","pillory squamomastoid","Michael Thompson","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2275","undertub hoboed","Janice Knowles","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2276","mealily cooboos","Claudio Cote","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2277","mealily cooboos","Claudio Cote","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2278","mealily cooboos","Claudio Cote","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2279","mealily cooboos","Claudio Cote","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2280","mealily cooboos","Claudio Cote","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2281","mealily cooboos","Claudio Cote","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2282","mealily cooboos","Claudio Cote","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2283","mealily cooboos","Claudio Cote","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2284","nonirrigated dampness","Debra Byrd","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2285","spoilages sanglier","Shelley Smith","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2286","liking initiatress","Nancy Chan","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2287","playa heiress","Shawn Kim","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2288","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2289","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2290","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2291","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2292","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2293","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2294","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2295","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2296","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2297","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2298","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2299","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2300","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2301","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2302","cadmus gentianales","David Jones","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2303","amphibia xerophthalmic","William Lewin","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2304","essays gld","Sherrill Haas","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2305","dullness spydom","Christine Thomas","Southampton");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2306","unstablished frousier","Tim Lawson","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2307","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2308","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2309","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2310","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2311","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2312","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2313","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2314","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2315","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2316","dawdle interludes","Debra Vannorman","Kingston upon Hull");

INSERT INTO Copies(copy_id,title,author,branch) VALUES("2317","dawdle interludes","Debra Vannorman","Kingston upon Hull");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2318","snitch grooper","Stephanie Loder","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2319","neonatology embowels","Eden Hinkson","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2320","unable unconsignable","Philip Bergevin","Nottingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2321","anticyclolysis shattery","Jeremy Kasper","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2322","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2323","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2324","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2325","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2326","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2327","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2328","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2329","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2330","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2331","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2332","prunetol aquarius","Bobbi Chapman","Coventry");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2333","simbil alcoholysis","Curt Hardebeck","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2334","pompon decadi","James Justus","Nottingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2335","mashru lignocaine","Connie Brown","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2336","siphonogama aposematically","Katherine Jones","London");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2337","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2338","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2339","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2340","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2341","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2342","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2343","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2344","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2345","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2346","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2347","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2348","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2349","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2350","riverway slunken","Thomas Park","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2351","playa heiress","Shawn Kim","Nottingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2352","mashru lignocaine","Connie Brown","Bristol");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2353","tesserarian chilidium","Gertrude Bradshaw","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2354","tythed ravison","Gerard Dicicco","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2355","magistracies forblow","Jon Lozano","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2356","magistracies forblow","Jon Lozano","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2357","magistracies forblow","Jon Lozano","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2358","magistracies forblow","Jon Lozano","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2359","merrytrotter coconspirator","Robert Davis","Edinburgh");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2360","joyce selfcide","Calvin Coury","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2361","restraightening fusing","John Peterson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2362","gluing gymsia","Julie Floyd","Birstall");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2363","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2364","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2365","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2366","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2367","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2368","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2369","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2370","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2371","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2372","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2373","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2374","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2375","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2376","madrassah sclerectomies","Alan Conyers","Leicester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2377","cassabanana meline","Robert Irwin","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2378","pilage misbehaves","Tom Foote","Caerdydd");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2379","megaloceros assay","James Staton","Glasgow");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2380","ultranationalist uneffusiveness","Sheri Miller","Reading");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2381","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2382","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2383","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2384","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2385","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2386","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2387","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2388","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2389","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2390","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2391","fecche teniacide","Raymond Richardson","Stoke-on-Trent");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2392","diagrammed noncoincident","Sherry Trotter","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2393","settees overmultiplying","Jane Richardson","Newcastle");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2394","dawdle interludes","Debra Vannorman","Birmingham");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2395","candollea poodler","Donna Mayhew","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2396","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2397","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2398","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2399","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2400","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2401","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2402","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2403","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2404","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2405","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2406","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2407","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2408","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2409","aptly zygotomere","Robert Rados","Portsmouth");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2410","unfurrowed tapayaxin","Judith Harris","Leeds");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2411","cyanophycin supervastness","Natalie Micciche","Manchester");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2412","phylonepionic malappropriation","Catherine Cray","Liverpool");
INSERT INTO Copies(copy_id,title,author,branch) VALUES("2413","restraightening fusing","John Peterson","Stoke-on-Trent");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_0","1337","86","2022-11-20","2022-11-30");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_2","1337","199","2022-12-21","2022-12-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_4","1337","111","2023-01-07","2023-02-05");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_6","1338","130","2022-11-20","2022-12-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_8","1338","145","2022-12-29","2023-01-25");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_10","1339","58","2022-11-20","2022-12-15");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_12","1339","133","2023-01-25","2023-02-25");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_14","1340","105","2022-11-20","2022-11-30");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_16","1340","186","2023-01-04","2023-01-08");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_18","1340","19","2023-02-10","2023-02-15");

INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_20","1341","72","2022-11-20","2022-11-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_22","1341","108","2022-12-13","2022-12-25");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_24","1341","195","2023-02-12","2023-02-14");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_26","1342","62","2022-11-20","2022-12-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_28","1342","132","2023-01-27","2023-02-09");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_30","1343","89","2022-11-20","2022-12-09");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_32","1343","76","2023-01-23","2023-02-17");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_34","1344","113","2022-11-20","2022-12-10");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_36","1344","117","2023-01-03","2023-01-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_38","1344","181","2023-02-02","2023-02-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_40","1345","94","2022-11-20","2022-11-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_42","1345","160","2022-12-30","2023-01-17");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_44","1345","110","2023-02-03","2023-02-18");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_46","1346","7","2022-11-20","2022-12-06");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_48","1346","136","2023-01-13","2023-02-07");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_50","1347","66","2022-11-20","2022-11-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_52","1347","157","2022-12-27","2023-01-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_54","1347","83","2023-02-13","2023-02-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_56","1348","2","2022-11-20","2022-12-19");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_58","1348","135","2023-02-06","2023-02-15");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_60","1349","145","2022-11-20","2022-12-08");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_62","1349","183","2022-12-28","2023-01-15");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_64","1350","18","2022-11-20","2022-12-03");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_66","1350","51","2022-12-23","2023-01-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_68","1350","35","2023-02-14","2023-02-20");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_70","1351","92","2022-11-20","2022-11-24");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_72","1351","92","2022-12-24","2023-01-17");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_74","1352","195","2022-11-20","2022-12-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_76","1352","90","2022-12-29","2023-01-05");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_78","1352","6","2023-01-17","2023-01-22");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_80","1353","6","2022-11-20","2022-12-05");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_82","1353","49","2022-12-17","2022-12-20");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_84","1353","139","2023-02-05","2023-02-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_86","1354","86","2022-11-20","2022-11-22");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_88","1354","11","2022-12-09","2022-12-30");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_90","1354","45","2023-01-31","2023-02-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_92","1355","185","2022-11-20","2022-12-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_94","1355","110","2023-01-07","2023-02-07");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_96","1356","134","2022-11-20","2022-12-17");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_98","1356","46","2022-12-31","2023-01-19");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_100","1357","136","2022-11-20","2022-11-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_102","1357","51","2023-01-09","2023-01-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_104","1358","80","2022-11-20","2022-12-20");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_106","1358","196","2023-01-03","2023-01-27");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_108","1359","72","2022-11-20","2022-12-17");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_110","1359","103","2023-01-17","2023-01-30");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_112","1360","121","2022-11-20","2022-11-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_114","1360","161","2022-12-22","2023-01-10");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_116","1360","135","2023-01-28","2023-02-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_118","1361","199","2022-11-20","2022-12-06");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_120","1361","193","2023-01-12","2023-01-24");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_122","1361","69","2023-02-11","2023-02-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_124","1362","68","2022-11-20","2022-11-27");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_126","1362","194","2023-01-14","2023-02-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_128","1363","146","2022-11-20","2022-12-19");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_130","1363","108","2023-02-01","2023-03-02");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_132","1364","151","2022-11-20","2022-12-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_134","1364","74","2023-01-07","2023-01-13");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_136","1364","187","2023-01-26","2023-02-07");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_138","1365","25","2022-11-20","2022-11-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_140","1365","126","2023-01-06","2023-01-26");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_142","1366","119","2022-11-20","2022-12-14");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_144","1366","120","2023-01-25","2023-02-11");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_146","1367","62","2022-11-20","2022-12-14");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_148","1367","193","2023-01-16","2023-01-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_150","1368","52","2022-11-20","2022-12-13");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_152","1368","169","2022-12-28","2023-01-09");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_154","1368","0","2023-02-08","2023-02-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_156","1369","5","2022-11-20","2022-12-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_158","1369","197","2023-01-02","2023-01-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_160","1370","35","2022-11-20","2022-12-14");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_162","1370","182","2023-01-20","2023-02-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_164","1371","134","2022-11-20","2022-12-17");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_166","1371","78","2023-01-01","2023-02-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_168","1372","85","2022-11-20","2022-12-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_170","1372","133","2023-01-11","2023-01-31");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_172","1373","82","2022-11-20","2022-12-06");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_174","1373","85","2023-01-15","2023-02-13");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_176","1374","177","2022-11-20","2022-11-26");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_178","1374","84","2022-12-12","2022-12-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_180","1374","8","2023-01-07","2023-01-12");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_182","1374","169","2023-01-24","2023-02-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_184","1375","184","2022-11-20","2022-12-03");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_186","1375","153","2023-01-13","2023-02-03");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_188","1376","34","2022-11-20","2022-11-29");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_190","1376","143","2022-12-28","2023-01-05");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_192","1377","156","2022-11-20","2022-11-22");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_194","1377","109","2022-12-11","2022-12-25");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_196","1377","70","2023-01-16","2023-01-25");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_198","1378","73","2022-11-20","2022-12-07");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_200","1378","53","2023-01-02","2023-01-31");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_202","1379","11","2022-11-20","2022-12-11");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_204","1379","150","2023-01-23","2023-01-29");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_206","1380","161","2022-11-20","2022-11-24");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_208","1380","184","2022-12-29","2023-01-08");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_210","1380","195","2023-02-17","2023-03-08");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_212","1381","143","2022-11-20","2022-11-22");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_214","1381","193","2023-01-05","2023-01-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_216","1382","195","2022-11-20","2022-12-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_218","1382","117","2023-01-15","2023-02-02");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_220","1383","30","2022-11-20","2022-11-26");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_222","1383","96","2023-01-04","2023-01-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_224","1383","17","2023-02-12","2023-02-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_226","1384","199","2022-11-20","2022-12-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_228","1384","186","2023-01-11","2023-01-29");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_230","1385","83","2022-11-20","2022-12-12");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_232","1385","58","2022-12-28","2023-01-08");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_234","1385","75","2023-02-17","2023-03-08");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_236","1386","100","2022-11-20","2022-11-30");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_238","1386","185","2022-12-31","2023-01-12");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_240","1387","47","2022-11-20","2022-12-03");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_242","1387","39","2023-01-05","2023-01-21");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_244","1388","16","2022-11-20","2022-12-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_246","1388","126","2023-01-03","2023-01-12");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_248","1388","34","2023-01-26","2023-02-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_250","1389","161","2022-11-20","2022-12-10");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_252","1389","182","2023-01-07","2023-01-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_254","1389","122","2023-02-01","2023-02-09");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_256","1390","83","2022-11-20","2022-12-07");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_258","1390","78","2023-01-02","2023-01-30");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_260","1391","98","2022-11-20","2022-12-10");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_262","1391","25","2023-01-02","2023-02-02");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_264","1392","44","2022-11-20","2022-12-03");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_266","1392","133","2023-01-04","2023-01-19");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_268","1393","150","2022-11-20","2022-12-19");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_270","1393","11","2023-01-22","2023-01-26");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_272","1394","17","2022-11-20","2022-12-19");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_274","1394","8","2023-01-25","2023-01-27");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_276","1395","85","2022-11-20","2022-12-10");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_278","1395","109","2022-12-25","2023-01-03");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_280","1395","64","2023-01-24","2023-02-22");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_282","1396","85","2022-11-20","2022-12-07");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_284","1396","127","2023-01-03","2023-01-21");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_286","1396","100","2023-02-08","2023-02-27");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_288","1397","167","2022-11-20","2022-12-12");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_290","1397","118","2023-01-12","2023-01-19");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_292","1397","145","2023-02-01","2023-03-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_294","1398","33","2022-11-20","2022-12-09");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_296","1398","57","2023-01-21","2023-02-18");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_298","1399","24","2022-11-20","2022-12-09");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_300","1399","165","2022-12-31","2023-01-31");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_302","1399","114","2023-02-18","2023-02-22");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_304","1400","4","2022-11-20","2022-12-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_306","1400","29","2022-12-13","2022-12-18");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_308","1400","22","2023-02-06","2023-03-06");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_310","1401","163","2022-11-20","2022-12-14");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_312","1401","183","2023-01-22","2023-02-11");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_314","1402","162","2022-11-20","2022-12-21");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_316","1402","28","2023-01-06","2023-01-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_318","1402","154","2023-02-09","2023-02-18");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_320","1403","115","2022-11-20","2022-11-24");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_322","1403","55","2023-01-08","2023-01-13");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_324","1404","4","2022-11-20","2022-12-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_326","1404","113","2023-01-19","2023-02-07");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_328","1405","3","2022-11-20","2022-12-17");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_330","1405","174","2023-01-22","2023-01-28");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_332","1406","115","2022-11-20","2022-12-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_334","1406","49","2023-01-30","2023-02-26");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_336","1407","160","2022-11-20","2022-12-10");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_338","1407","68","2023-01-11","2023-02-06");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_340","1408","140","2022-11-20","2022-12-09");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_342","1408","167","2022-12-28","2023-01-24");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_344","1409","180","2022-11-20","2022-12-01");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_346","1409","96","2022-12-28","2023-01-08");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_348","1409","184","2023-01-31","2023-02-13");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_350","1410","132","2022-11-20","2022-12-08");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_352","1410","173","2023-01-24","2023-02-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_354","1411","185","2022-11-20","2022-12-11");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_356","1411","57","2023-01-06","2023-01-24");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_358","1412","184","2022-11-20","2022-12-12");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_360","1412","96","2023-01-20","2023-02-14");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_362","1413","198","2022-11-20","2022-12-16");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_364","1413","33","2023-01-21","2023-02-19");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_366","1414","41","2022-11-20","2022-11-22");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_368","1414","72","2023-01-11","2023-01-23");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_370","1414","6","2023-02-08","2023-03-05");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_372","1415","76","2022-11-20","2022-12-04");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_374","1415","175","2022-12-22","2022-12-25");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_376","1415","36","2023-02-06","2023-02-09");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_378","1416","186","2022-11-20","2022-12-18");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_380","1416","195","2023-01-27","2023-02-03");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_382","1417","159","2022-11-20","2022-12-07");
INSERT INTO Loans(loan_id,copy,customer,start,due) VALUES("loan_384","1417","150","2022-12-21","2022-12-25");

INSERT INTO Returns(loan,date) VALUES("loan_4784","2023-02-03");
INSERT INTO Returns(loan,date) VALUES("loan_4786","2022-11-24");
INSERT INTO Returns(loan,date) VALUES("loan_4788","2023-02-13");
INSERT INTO Returns(loan,date) VALUES("loan_4790","2022-11-30");
INSERT INTO Returns(loan,date) VALUES("loan_4792","2023-01-24");
INSERT INTO Returns(loan,date) VALUES("loan_4794","2022-12-03");
INSERT INTO Returns(loan,date) VALUES("loan_4796","2023-01-02");
INSERT INTO Returns(loan,date) VALUES("loan_4798","2022-11-26");
INSERT INTO Returns(loan,date) VALUES("loan_4800","2023-02-11");
INSERT INTO Returns(loan,date) VALUES("loan_4802","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_4804","2023-01-16");
INSERT INTO Returns(loan,date) VALUES("loan_4806","2023-02-08");
INSERT INTO Returns(loan,date) VALUES("loan_4808","2022-12-02");
INSERT INTO Returns(loan,date) VALUES("loan_4810","2023-01-30");
INSERT INTO Returns(loan,date) VALUES("loan_4812","2022-11-30");
INSERT INTO Returns(loan,date) VALUES("loan_4814","2023-02-11");
INSERT INTO Returns(loan,date) VALUES("loan_4816","2022-12-01");
INSERT INTO Returns(loan,date) VALUES("loan_4818","2023-02-07");
INSERT INTO Returns(loan,date) VALUES("loan_4820","2022-12-06");
INSERT INTO Returns(loan,date) VALUES("loan_4822","2023-01-16");
INSERT INTO Returns(loan,date) VALUES("loan_4824","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_4826","2022-12-30");
INSERT INTO Returns(loan,date) VALUES("loan_4828","2023-02-13");
INSERT INTO Returns(loan,date) VALUES("loan_4830","2022-11-26");
INSERT INTO Returns(loan,date) VALUES("loan_4834","2023-02-24");
INSERT INTO Returns(loan,date) VALUES("loan_4836","2022-12-06");
INSERT INTO Returns(loan,date) VALUES("loan_4838","2023-01-27");
INSERT INTO Returns(loan,date) VALUES("loan_4840","2022-11-27");
INSERT INTO Returns(loan,date) VALUES("loan_4842","2023-02-13");
INSERT INTO Returns(loan,date) VALUES("loan_4844","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_4846","2023-02-23");
INSERT INTO Returns(loan,date) VALUES("loan_4848","2022-12-05");
INSERT INTO Returns(loan,date) VALUES("loan_4850","2023-01-16");
INSERT INTO Returns(loan,date) VALUES("loan_4852","2022-12-04");
INSERT INTO Returns(loan,date) VALUES("loan_4854","2023-01-12");
INSERT INTO Returns(loan,date) VALUES("loan_4856","2022-12-04");
INSERT INTO Returns(loan,date) VALUES("loan_4858","2022-12-29");
INSERT INTO Returns(loan,date) VALUES("loan_4860","2022-12-06");
INSERT INTO Returns(loan,date) VALUES("loan_4862","2023-01-24");
INSERT INTO Returns(loan,date) VALUES("loan_4864","2022-11-25");
INSERT INTO Returns(loan,date) VALUES("loan_4866","2022-12-29");
INSERT INTO Returns(loan,date) VALUES("loan_4868","2023-01-31");
INSERT INTO Returns(loan,date) VALUES("loan_4870","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_4872","2023-01-15");
INSERT INTO Returns(loan,date) VALUES("loan_4874","2022-11-29");
INSERT INTO Returns(loan,date) VALUES("loan_4876","2023-01-25");
INSERT INTO Returns(loan,date) VALUES("loan_4878","2023-02-13");
INSERT INTO Returns(loan,date) VALUES("loan_4880","2022-12-01");
INSERT INTO Returns(loan,date) VALUES("loan_4882","2022-12-29");
INSERT INTO Returns(loan,date) VALUES("loan_4884","2022-11-30");
INSERT INTO Returns(loan,date) VALUES("loan_4886","2023-01-16");
INSERT INTO Returns(loan,date) VALUES("loan_4888","2022-11-24");
INSERT INTO Returns(loan,date) VALUES("loan_4890","2022-12-26");
INSERT INTO Returns(loan,date) VALUES("loan_4892","2023-02-13");
INSERT INTO Returns(loan,date) VALUES("loan_4894","2022-11-29");
INSERT INTO Returns(loan,date) VALUES("loan_4896","2023-01-30");
INSERT INTO Returns(loan,date) VALUES("loan_4898","2022-12-05");
INSERT INTO Returns(loan,date) VALUES("loan_4900","2022-12-14");
INSERT INTO Returns(loan,date) VALUES("loan_4902","2023-02-03");
INSERT INTO Returns(loan,date) VALUES("loan_4904","2022-12-06");
INSERT INTO Returns(loan,date) VALUES("loan_4906","2023-02-09");
INSERT INTO Returns(loan,date) VALUES("loan_4908","2022-11-30");
INSERT INTO Returns(loan,date) VALUES("loan_4910","2023-01-28");
INSERT INTO Returns(loan,date) VALUES("loan_4912","2022-11-25");
INSERT INTO Returns(loan,date) VALUES("loan_4914","2023-01-01");
INSERT INTO Returns(loan,date) VALUES("loan_4916","2023-02-06");
INSERT INTO Returns(loan,date) VALUES("loan_4918","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_4920","2023-01-17");
INSERT INTO Returns(loan,date) VALUES("loan_4922","2022-12-02");
INSERT INTO Returns(loan,date) VALUES("loan_4924","2023-01-17");
INSERT INTO Returns(loan,date) VALUES("loan_4926","2023-02-20");
INSERT INTO Returns(loan,date) VALUES("loan_4928","2022-11-25");
INSERT INTO Returns(loan,date) VALUES("loan_4930","2023-01-24");
INSERT INTO Returns(loan,date) VALUES("loan_4932","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_4934","2022-12-28");
INSERT INTO Returns(loan,date) VALUES("loan_4936","2023-02-13");
INSERT INTO Returns(loan,date) VALUES("loan_4938","2022-12-02");
INSERT INTO Returns(loan,date) VALUES("loan_4940","2023-01-10");
INSERT INTO Returns(loan,date) VALUES("loan_4942","2023-02-25");
INSERT INTO Returns(loan,date) VALUES("loan_4944","2022-12-07");
INSERT INTO Returns(loan,date) VALUES("loan_4946","2023-01-11");
INSERT INTO Returns(loan,date) VALUES("loan_4948","2023-02-11");
INSERT INTO Returns(loan,date) VALUES("loan_4950","2022-11-22");
INSERT INTO Returns(loan,date) VALUES("loan_4952","2022-12-29");
INSERT INTO Returns(loan,date) VALUES("loan_4954","2023-02-27");
INSERT INTO Returns(loan,date) VALUES("loan_4956","2022-11-27");
INSERT INTO Returns(loan,date) VALUES("loan_4958","2023-01-19");
INSERT INTO Returns(loan,date) VALUES("loan_4960","2023-02-24");
INSERT INTO Returns(loan,date) VALUES("loan_4962","2022-12-07");
INSERT INTO Returns(loan,date) VALUES("loan_4964","2022-12-22");
INSERT INTO Returns(loan,date) VALUES("loan_4966","2022-11-27");
INSERT INTO Returns(loan,date) VALUES("loan_4968","2023-01-19");
INSERT INTO Returns(loan,date) VALUES("loan_4970","2023-02-11");
INSERT INTO Returns(loan,date) VALUES("loan_4972","2022-11-22");
INSERT INTO Returns(loan,date) VALUES("loan_4974","2023-01-03");
INSERT INTO Returns(loan,date) VALUES("loan_4976","2022-12-07");
INSERT INTO Returns(loan,date) VALUES("loan_4978","2023-01-29");
INSERT INTO Returns(loan,date) VALUES("loan_4982","2023-01-09");
INSERT INTO Returns(loan,date) VALUES("loan_4984","2023-02-20");
INSERT INTO Returns(loan,date) VALUES("loan_4986","2022-12-04");
INSERT INTO Returns(loan,date) VALUES("loan_4988","2023-01-07");
INSERT INTO Returns(loan,date) VALUES("loan_4990","2022-11-28");
INSERT INTO Returns(loan,date) VALUES("loan_4992","2023-01-16");
INSERT INTO Returns(loan,date) VALUES("loan_4994","2022-12-07");
INSERT INTO Returns(loan,date) VALUES("loan_4996","2023-01-23");
INSERT INTO Returns(loan,date) VALUES("loan_4998","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_5000","2023-01-28");
INSERT INTO Returns(loan,date) VALUES("loan_5002","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_5004","2022-12-27");
INSERT INTO Returns(loan,date) VALUES("loan_5006","2023-02-24");
INSERT INTO Returns(loan,date) VALUES("loan_5008","2022-12-02");
INSERT INTO Returns(loan,date) VALUES("loan_5010","2023-01-26");
INSERT INTO Returns(loan,date) VALUES("loan_5012","2022-11-30");
INSERT INTO Returns(loan,date) VALUES("loan_5014","2023-02-01");
INSERT INTO Returns(loan,date) VALUES("loan_5016","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_5018","2023-01-14");
INSERT INTO Returns(loan,date) VALUES("loan_5020","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_5022","2022-12-30");
INSERT INTO Returns(loan,date) VALUES("loan_5024","2023-01-30");
INSERT INTO Returns(loan,date) VALUES("loan_5026","2022-11-29");
INSERT INTO Returns(loan,date) VALUES("loan_5028","2022-12-31");
INSERT INTO Returns(loan,date) VALUES("loan_5030","2022-12-04");
INSERT INTO Returns(loan,date) VALUES("loan_5032","2022-12-24");
INSERT INTO Returns(loan,date) VALUES("loan_5034","2023-02-25");
INSERT INTO Returns(loan,date) VALUES("loan_5036","2022-12-01");
INSERT INTO Returns(loan,date) VALUES("loan_5038","2023-01-04");
INSERT INTO Returns(loan,date) VALUES("loan_5040","2022-12-01");
INSERT INTO Returns(loan,date) VALUES("loan_5042","2023-01-17");
INSERT INTO Returns(loan,date) VALUES("loan_5044","2023-02-01");
INSERT INTO Returns(loan,date) VALUES("loan_5046","2022-11-29");
INSERT INTO Returns(loan,date) VALUES("loan_5048","2023-01-13");
INSERT INTO Returns(loan,date) VALUES("loan_5050","2023-02-21");
INSERT INTO Returns(loan,date) VALUES("loan_5052","2022-12-04");
INSERT INTO Returns(loan,date) VALUES("loan_5054","2023-01-17");
INSERT INTO Returns(loan,date) VALUES("loan_5056","2023-02-24");
INSERT INTO Returns(loan,date) VALUES("loan_5058","2022-11-30");
INSERT INTO Returns(loan,date) VALUES("loan_5060","2023-01-18");
INSERT INTO Returns(loan,date) VALUES("loan_5062","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_5064","2022-12-30");
INSERT INTO Returns(loan,date) VALUES("loan_5066","2022-12-07");
INSERT INTO Returns(loan,date) VALUES("loan_5068","2023-01-03");
INSERT INTO Returns(loan,date) VALUES("loan_5070","2023-02-10");
INSERT INTO Returns(loan,date) VALUES("loan_5072","2022-12-02");
INSERT INTO Returns(loan,date) VALUES("loan_5074","2023-02-04");
INSERT INTO Returns(loan,date) VALUES("loan_5076","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_5078","2023-01-19");
INSERT INTO Returns(loan,date) VALUES("loan_5080","2022-12-05");
INSERT INTO Returns(loan,date) VALUES("loan_5082","2023-02-01");
INSERT INTO Returns(loan,date) VALUES("loan_5084","2022-12-05");
INSERT INTO Returns(loan,date) VALUES("loan_5086","2023-01-06");
INSERT INTO Returns(loan,date) VALUES("loan_5088","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_5090","2023-01-10");
INSERT INTO Returns(loan,date) VALUES("loan_5092","2023-03-03");
INSERT INTO Returns(loan,date) VALUES("loan_5094","2022-11-30");
INSERT INTO Returns(loan,date) VALUES("loan_5096","2023-02-02");
INSERT INTO Returns(loan,date) VALUES("loan_5098","2022-11-28");
INSERT INTO Returns(loan,date) VALUES("loan_5100","2023-02-01");
INSERT INTO Returns(loan,date) VALUES("loan_5102","2022-11-22");
INSERT INTO Returns(loan,date) VALUES("loan_5104","2023-01-12");
INSERT INTO Returns(loan,date) VALUES("loan_5106","2022-11-28");
INSERT INTO Returns(loan,date) VALUES("loan_5108","2022-12-20");
INSERT INTO Returns(loan,date) VALUES("loan_5110","2023-02-01");
INSERT INTO Returns(loan,date) VALUES("loan_5112","2022-12-07");
INSERT INTO Returns(loan,date) VALUES("loan_5114","2023-01-30");
INSERT INTO Returns(loan,date) VALUES("loan_5116","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_5118","2023-01-06");
INSERT INTO Returns(loan,date) VALUES("loan_5120","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_5122","2023-01-28");
INSERT INTO Returns(loan,date) VALUES("loan_5124","2023-02-06");
INSERT INTO Returns(loan,date) VALUES("loan_5126","2022-12-04");
INSERT INTO Returns(loan,date) VALUES("loan_5128","2023-01-20");
INSERT INTO Returns(loan,date) VALUES("loan_5130","2022-12-03");
INSERT INTO Returns(loan,date) VALUES("loan_5132","2023-01-14");
INSERT INTO Returns(loan,date) VALUES("loan_5134","2022-11-27");
INSERT INTO Returns(loan,date) VALUES("loan_5136","2023-01-29");
INSERT INTO Returns(loan,date) VALUES("loan_5138","2022-11-29");
INSERT INTO Returns(loan,date) VALUES("loan_5140","2023-01-19");
INSERT INTO Returns(loan,date) VALUES("loan_5142","2022-12-05");
INSERT INTO Returns(loan,date) VALUES("loan_5144","2023-01-10");
INSERT INTO Returns(loan,date) VALUES("loan_5146","2023-03-07");
INSERT INTO Returns(loan,date) VALUES("loan_5148","2022-12-04");
INSERT INTO Returns(loan,date) VALUES("loan_5150","2023-01-15");
INSERT INTO Returns(loan,date) VALUES("loan_5152","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_5154","2023-01-17");
INSERT INTO Returns(loan,date) VALUES("loan_5156","2022-11-29");
INSERT INTO Returns(loan,date) VALUES("loan_5158","2023-01-18");
INSERT INTO Returns(loan,date) VALUES("loan_5160","2023-02-28");
INSERT INTO Returns(loan,date) VALUES("loan_5162","2022-11-29");
INSERT INTO Returns(loan,date) VALUES("loan_5164","2023-01-24");
INSERT INTO Returns(loan,date) VALUES("loan_5166","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_5168","2023-01-07");
INSERT INTO Returns(loan,date) VALUES("loan_5170","2022-11-23");
INSERT INTO Returns(loan,date) VALUES("loan_5172","2022-12-29");
INSERT INTO Returns(loan,date) VALUES("loan_5174","2023-02-15");
INSERT INTO Returns(loan,date) VALUES("loan_5176","2022-11-22");
INSERT INTO Returns(loan,date) VALUES("loan_5178","2023-01-29");
INSERT INTO Returns(loan,date) VALUES("loan_5180","2022-11-30");
INSERT INTO Returns(loan,date) VALUES("loan_5182","2023-01-11");
INSERT INTO Returns(loan,date) VALUES("loan_5184","2023-02-23");
INSERT INTO Returns(loan,date) VALUES("loan_5186","2022-12-03");
INSERT INTO Returns(loan,date) VALUES("loan_5188","2023-02-17");
INSERT INTO Returns(loan,date) VALUES("loan_5190","2022-11-21");
INSERT INTO Returns(loan,date) VALUES("loan_5192","2023-01-25");
INSERT INTO Returns(loan,date) VALUES("loan_5194","2023-03-01");
INSERT INTO Returns(loan,date) VALUES("loan_5196","2022-12-03");
INSERT INTO Returns(loan,date) VALUES("loan_5198","2023-02-03");
INSERT INTO Returns(loan,date) VALUES("loan_5200","2023-02-18");
INSERT INTO Returns(loan,date) VALUES("loan_5202","2022-12-03");
INSERT INTO Returns(loan,date) VALUES("loan_5204","2023-01-30");
INSERT INTO Returns(loan,date) VALUES("loan_5206","2023-02-13");
INSERT INTO Returns(loan,date) VALUES("loan_5208","2022-12-01");
INSERT INTO Returns(loan,date) VALUES("loan_5210","2023-01-29");
INSERT INTO Returns(loan,date) VALUES("loan_5212","2022-12-01");
INSERT INTO Returns(loan,date) VALUES("loan_5214","2023-01-30");
INSERT INTO Returns(loan,date) VALUES("loan_5216","2022-11-27");
INSERT INTO Returns(loan,date) VALUES("loan_5218","2023-01-24");
INSERT INTO Returns(loan,date) VALUES("loan_5220","2022-11-24");
INSERT INTO Returns(loan,date) VALUES("loan_5222","2023-02-03");
INSERT INTO Returns(loan,date) VALUES("loan_5224","2024-01-03");
INSERT INTO Returns(loan,date) VALUES("loan_5226","2024-01-26");
INSERT INTO Returns(loan,date) VALUES("loan_5230","2024-03-12");
INSERT INTO Returns(loan,date) VALUES("loan_5232","2024-04-04");
INSERT INTO Returns(loan,date) VALUES("loan_5234","2024-04-27");
INSERT INTO Returns(loan,date) VALUES("loan_5236","2024-05-20");
INSERT INTO Returns(loan,date) VALUES("loan_5238","2024-06-12");
INSERT INTO Returns(loan,date) VALUES("loan_5240","2024-07-05");
INSERT INTO Returns(loan,date) VALUES("loan_5242","2024-07-28");
INSERT INTO Returns(loan,date) VALUES("loan_5244","2024-08-20");
INSERT INTO Returns(loan,date) VALUES("loan_5246","2024-09-12");
INSERT INTO Returns(loan,date) VALUES("loan_5248","2024-10-05");
INSERT INTO Returns(loan,date) VALUES("loan_5250","2024-10-28");
INSERT INTO Returns(loan,date) VALUES("loan_5254","2024-12-13");
INSERT INTO Returns(loan,date) VALUES("loan_5256","2025-01-05");
INSERT INTO Returns(loan,date) VALUES("loan_5258","2025-01-28");
INSERT INTO Returns(loan,date) VALUES("loan_5260","2025-02-20");
INSERT INTO Returns(loan,date) VALUES("loan_5262","2025-03-15");
INSERT INTO Returns(loan,date) VALUES("loan_5264","2025-04-07");
INSERT INTO Returns(loan,date) VALUES("loan_5266","2025-04-30");
INSERT INTO Returns(loan,date) VALUES("loan_5268","2025-05-23");
INSERT INTO Returns(loan,date) VALUES("loan_5270","2025-06-15");
INSERT INTO Returns(loan,date) VALUES("loan_5272","2025-07-08");
INSERT INTO Returns(loan,date) VALUES("loan_5274","2025-08-09");
INSERT INTO Returns(loan,date) VALUES("loan_5276","2025-09-08");
INSERT INTO Returns(loan,date) VALUES("loan_5278","2025-10-08");
INSERT INTO Returns(loan,date) VALUES("loan_5280","2025-11-07");
INSERT INTO Returns(loan,date) VALUES("loan_5282","2025-12-07");
INSERT INTO Returns(loan,date) VALUES("loan_5284","2026-01-06");
INSERT INTO Returns(loan,date) VALUES("loan_5286","2026-02-05");
INSERT INTO Returns(loan,date) VALUES("loan_5288","2026-03-07");
INSERT INTO Returns(loan,date) VALUES("loan_5290","2026-04-06");
INSERT INTO Returns(loan,date) VALUES("loan_5292","2026-05-06");
INSERT INTO Returns(loan,date) VALUES("loan_5294","2026-06-05");
INSERT INTO Returns(loan,date) VALUES("loan_5296","2026-07-05");
INSERT INTO Returns(loan,date) VALUES("loan_5298","2026-08-04");
INSERT INTO Returns(loan,date) VALUES("loan_5300","2026-09-03");
INSERT INTO Returns(loan,date) VALUES("loan_5302","2026-10-03");
INSERT INTO Returns(loan,date) VALUES("loan_5304","2026-11-02");
INSERT INTO Returns(loan,date) VALUES("loan_5306","2026-12-02");
INSERT INTO Returns(loan,date) VALUES("loan_5308","2027-01-01");
INSERT INTO Returns(loan,date) VALUES("loan_5310","2027-01-31");
INSERT INTO Returns(loan,date) VALUES("loan_5312","2027-03-02");
INSERT INTO Returns(loan,date) VALUES("loan_5314","2027-04-01");
INSERT INTO Returns(loan,date) VALUES("loan_5316","2027-05-01");
INSERT INTO Returns(loan,date) VALUES("loan_5318","2027-05-31");
INSERT INTO Returns(loan,date) VALUES("loan_5320","2027-06-30");
INSERT INTO Returns(loan,date) VALUES("loan_5322","2027-07-30");
INSERT INTO Returns(loan,date) VALUES("loan_5324","2027-08-29");
INSERT INTO Returns(loan,date) VALUES("loan_5326","2027-09-28");
INSERT INTO Returns(loan,date) VALUES("loan_5328","2027-10-28");
INSERT INTO Returns(loan,date) VALUES("loan_5330","2027-11-27");
INSERT INTO Returns(loan,date) VALUES("loan_5332","2027-12-27");
INSERT INTO Holds(customer,title,author,queue) VALUES("30","kansans radiology","Laura Goodall",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("154","undertub hoboed","Janice Knowles",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("121","saronide forficated","Rosetta Mitchell",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("2","eably admiring","Rose Sorrels",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("125","megillah interlocutrix","John Glass",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("60","hippopotamuses bejewel","Mary Johnson",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("62","diazonium chamaerops","Carolyn Sullivan",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("72","sugarhouse megaseismic","Rhonda Lones",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("67","undreadfully microsthenes","Michael King",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("144","postmeridional aimed","Keith Anderson",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("83","aptly zygotomere","Robert Rados",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("27","cephalodiscida toryfy","Carol Guzman",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("73","dissemblers bluestockings","Dino Schwalbe",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("175","chancefully crayonist","William Miller",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("187","gluing gymsia","Julie Floyd",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("0","mucose undigestion","Trevor Ceron",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("32","kerrite schismatize","Jean Bigler",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("130","nonreticently lindsay","Eddie Strzelecki",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("177","fecche teniacide","Raymond Richardson",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("94","karroo superstrain","Thomas Christy",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("153","nonhunting hoarstone","Gwendolyn Pollard",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("133","kansans radiology","Laura Goodall",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("105","explicative gladded","Leslie Wisner",1);

INSERT INTO Holds(customer,title,author,queue) VALUES("82","anserin repealability","Katie Gunn",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("118","mealily cooboos","Claudio Cote",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("12","chancefully crayonist","William Miller",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("198","beefcake gonococcus","Jonathan Peck",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("163","silhouettograph semiflexure","Nancy Pasch",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("136","nonreticently lindsay","Eddie Strzelecki",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("124","supraworld siphonaria","Jose Mills",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("34","oleander unespied","Tommie Bright",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("55","masterling declaiming","Donald White",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("112","smallen lilacthroat","Janice Macdonald",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("23","hexachord leverer","Robin Eitniear",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("159","pearlfish irrupted","Glenda French",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("182","aglucone misaccount","Betty Catanzarite",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("150","aglucone misaccount","Betty Catanzarite",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("114","yeshiva symmetrization","Richard Fouse",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("28","unable unconsignable","Philip Bergevin",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("49","misguesses jackeen","Antonio Santiago",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("4","embeddable jotisaru","Linda Spencer",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("36","explicative gladded","Leslie Wisner",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("142","coxalgia unlikelihood","Janet Rose",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("165","muscicolous menehune","Laura Taylor",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("37","megaloceros assay","James Staton",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("101","unarousable inequicostate","Patricia Duffin",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("68","woon ballyragging","Michael Velasquez",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("184","unfurrowed tapayaxin","Judith Harris",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("199","featishness radiostrontium","Kay Rushing",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("59","histophysiologic asuri","Rachel Johnson",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("106","mirkiest anour","Angela Brock",3);
INSERT INTO Holds(customer,title,author,queue) VALUES("155","riverway slunken","Thomas Park",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("170","mirkiest anour","Angela Brock",4);
INSERT INTO Holds(customer,title,author,queue) VALUES("139","radicalized presupposition","Charles Johnson",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("64","smallen lilacthroat","Janice Macdonald",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("91","filthier original","Ida Wheeler",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("117","overcorrupt docibleness","Raymond Anderson",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("109","undertub hoboed","Janice Knowles",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("181","expression ayubite","Peter George",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("52","saturnine monotonousness","Martina Vitullo",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("147","nordenskioldine pedalling","Helena Monteleone",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("13","prehistorical clivias","Joyce Tanner",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("84","saronide forficated","Rosetta Mitchell",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("193","settees overmultiplying","Jane Richardson",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("50","snitch grooper","Stephanie Loder",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("77","ectogenic relented","Alison Coffman",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("56","bookmate spiderier","Luke Blodgett",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("120","coxalgia unlikelihood","Janet Rose",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("188","kerrite schismatize","Jean Bigler",3);
INSERT INTO Holds(customer,title,author,queue) VALUES("51","adjoined archprimate","Randy Jacoby",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("152","redivulge tenontomyoplasty","Cody Kamerer",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("8","lachrymae dunged","James Jones",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("186","kinoplasmic liodermia","Thaddeus Scott",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("134","megaloceros assay","James Staton",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("86","ectomesoblast distune","Alonzo Bench",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("173","perityphlic sclerotic","John Vargas",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("54","anticyclolysis shattery","Jeremy Kasper",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("127","mystified oxalonitril","Joshua Daugherty",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("123","eucosmid missteered","Gladys Fischer",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("119","mystified oxalonitril","Joshua Daugherty",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("69","myxogastres interchain","Margot Drake",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("11","madrassah sclerectomies","Alan Conyers",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("113","nonhunting hoarstone","Gwendolyn Pollard",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("79","lachrymae dunged","James Jones",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("3","aptly zygotomere","Robert Rados",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("115","rededicated intrapericardiac","David Powell",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("18","mucose undigestion","Trevor Ceron",3);
INSERT INTO Holds(customer,title,author,queue) VALUES("190","marginal publicization","Theodore Hernandez",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("61","blitzkrieg erses","Sherryl Holloway",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("87","karroo superstrain","Thomas Christy",3);
INSERT INTO Holds(customer,title,author,queue) VALUES("192","mirkiest anour","Angela Brock",5);
INSERT INTO Holds(customer,title,author,queue) VALUES("81","protuberantness anfractuosity","Ana Champlin",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("196","slateful superfinancing","Ruby Fortson",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("76","prunetol aquarius","Bobbi Chapman",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("1","disenthralled disenthronement","William Omara",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("189","acolytus crud","Edward Price",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("104","resinol bede","Betty Jensen",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("7","hyperparathyroidism pilate","Tim Kindle",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("89","plateasm cryable","Robert Munson",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("143","marginal publicization","Theodore Hernandez",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("43","dullness spydom","Christine Thomas",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("194","pillory squamomastoid","Michael Thompson",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("14","hexachord leverer","Robin Eitniear",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("46","pilage misbehaves","Tom Foote",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("74","explicative gladded","Leslie Wisner",3);
INSERT INTO Holds(customer,title,author,queue) VALUES("24","unremote fifth","Dorothea King",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("5","joyce selfcide","Calvin Coury",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("161","phylonepionic malappropriation","Catherine Cray",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("38","mealily cooboos","Claudio Cote",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("157","hyperparathyroidism pilate","Tim Kindle",3);
INSERT INTO Holds(customer,title,author,queue) VALUES("39","transversely genu","Alexandra Henry",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("35","missable propheticality","Martin Priest",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("93","enframes burrhead","Harold Giard",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("107","saturnine monotonousness","Martina Vitullo",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("156","fecche teniacide","Raymond Richardson",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("95","filthier original","Ida Wheeler",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("174","splashwing antitheistic","Dianne Clay",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("103","nonunification trilobated","George Grubaugh",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("140","scolopendrelloid gabbai","Eloy Sexton",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("122","nonreticently lindsay","Eddie Strzelecki",3);
INSERT INTO Holds(customer,title,author,queue) VALUES("132","acolytus crud","Edward Price",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("179","nonreticently lindsay","Eddie Strzelecki",4);
INSERT INTO Holds(customer,title,author,queue) VALUES("88","dizain taperness","Rosa Montville",2);
INSERT INTO Holds(customer,title,author,queue) VALUES("100","fecklessly beachboys","Marcus Pritchard",1);
INSERT INTO Holds(customer,title,author,queue) VALUES("17","fecche teniacide","Raymond Richardson",3);

In [17]:
cust_string = cust_string.replace("\"","\'")

In [18]:
for y in range(len(df_loans)):
    val = str(df_loans.loc[y,"startdate"])
    val = val.split("-")
    ts = pd.Timestamp(year = int(val[0]),  month = int(val[1]), day = int(val[2]), tz = 'GMT') 
    
    df_loans.loc[y,"startdate"] = (ts.to_julian_date())
    
    val = str(df_loans.loc[y,"enddate"])
    val = val.split("-")
    ts = pd.Timestamp(year = int(val[0]),  month = int(val[1]), day = int(val[2]), tz = 'GMT') 
    
    df_loans.loc[y,"enddate"] = (ts.to_julian_date())

for y in range(len(df_returns)):
    val = str(df_returns.loc[y,"date"])
    val = val.split("-")
    ts = pd.Timestamp(year = int(val[0]),  month = int(val[1]), day = int(val[2]), tz = 'GMT') 
    
    df_returns.loc[y,"date"] = (ts.to_julian_date())

In [19]:
#Creating the files


# Path
path = os.path.join(parent_dir, directory)

# Path
try:
    os.mkdir(directory)
    print("Directory '% s' created" % directory)
except:
    print("already exists :)")

# Export

base = path+"/"

df_cust.to_csv(base+"cust.csv",index=False,header=False)
df_books.to_csv(base+"books.csv",index=False,header=False)
df_copies.to_csv(base+"copies.csv",index=False,header=False)
df_loans.to_csv(base+"loan.csv",index=False,header=False)
df_hold.to_csv(base+"holds.csv",index=False,header=False)
df_returns.to_csv(base+"returns.csv",index=False,header=False)


#the inserts for equivlent sql schema 
text_file = open(base+"inserts.txt", "w")
n = text_file.write(cust_string)
text_file.close()

print("***CREATE COMPLETE****")

already exists :)
***CREATE COMPLETE****